apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-apikey
    namespace: default
type: Opaque
data:
    API_KEY: ENC[AES256_GCM,data:RKcQyqsu2XDdn5y6KDO1hWvfqlNB/oBX4mKh8cgobMjuuh7s0AOGURx72hE=,iv:vMwwfRNEo+wH0oYmKts13EuwCuPgeELqbiLohTg9jMs=,tag:ow2Am8sXxuAAxSkdqtnn2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19jc9zp5pc7me0wkx28kc2ypr9qh6t9zphn3fdk63ae9dz9a2h5gsh4w866
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4L25WTU1wN2YxU0V5MG1m
            dHJtZkZvTENqUk1ndmozaWIwRGNFZFhGSFJRCnJIY0VsTlNkRnp2bEd3Y0RlRDdG
            TDlKT3B2QTdxa2lVVDRhb1VGU2xSYVUKLS0tIHVzRFR4OVYvVTdFcS9KVkxucytr
            VUxETUthYmh4b2QycnU5T0hKVmJlQ28Ks7nUV0RyfKJozVZS5TuyD5+KCU59dAFv
            Uu2zOoWf9ih0Mi85pNeFeZSIfppeZADBXbJJ7XtxGAIp5jzY4m5Ipg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-03T14:28:02Z"
    mac: ENC[AES256_GCM,data:5HvVa5BDnwiaNBTH3v3MbPAHZqTUouFAWPtrYV1ftGBAvXAACfOv/SVfPxMf4Aw4rl3fpGyulprCNaG/x61Y8FAan2K9j/H5US17gbVINMMAvYNmjKWmn2tqap4xltVCwuwBQ9dypbdCrEpbpa+DjkyIMdp1Yri4k8Ie5ehuIi0=,iv:S7vwLcMU8ogwvKOLcwOF1JWI0ix3F3VNzbbkx5U3JJk=,tag:91570V0IsXVunmv7GWyJ1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
