apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-apikey
    namespace: default
type: Opaque
data:
    APIKEY: ENC[AES256_GCM,data:RLcawkHfkk0tmjBcC3/o9u2/T32CcmjS0yUF8GHYsq3j5/jH9IFd3lPImiI=,iv:EzQMX2PKQt71lPXFDr0Lz28LKOB2uW/682HUPfhQ7+g=,tag:TP7VLvqDnHBuJsMf9n76AA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19jc9zp5pc7me0wkx28kc2ypr9qh6t9zphn3fdk63ae9dz9a2h5gsh4w866
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4L25WTU1wN2YxU0V5MG1m
            dHJtZkZvTENqUk1ndmozaWIwRGNFZFhGSFJRCnJIY0VsTlNkRnp2bEd3Y0RlRDdG
            TDlKT3B2QTdxa2lVVDRhb1VGU2xSYVUKLS0tIHVzRFR4OVYvVTdFcS9KVkxucytr
            VUxETUthYmh4b2QycnU5T0hKVmJlQ28Ks7nUV0RyfKJozVZS5TuyD5+KCU59dAFv
            Uu2zOoWf9ih0Mi85pNeFeZSIfppeZADBXbJJ7XtxGAIp5jzY4m5Ipg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-03T04:06:04Z"
    mac: ENC[AES256_GCM,data:nGSl0s241InfUP6hl+fY+wQMqEpOusZRhoUaEuljvcpmjEfg9csOxMZonb674cVYXCor1CxOTVQW3HWrQtIL1bGp3ZfgEnTV1HOWjaxwNlcpAcgZ98Ed+NtEYB5h5ocbzPRkgufBZft56Lvta6+i4SwnQ4lwUvWT7P8tLX+IFOM=,iv:WF2glLZ7CJH2ytQKNLwD9xGyucgksBqsqc/L8sj7dVE=,tag:VlDJIy+MStT93I4v5lLtYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
