apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-apikey
    namespace: default
type: Opaque
stringData:
    APIKEY: ENC[AES256_GCM,data:pMg0,iv:+OndVUhYH2+VsdVF3agHnf2myr+fyZ54QHOQ+3UP7j0=,tag:K2nA1PJZ/SgjMJvs0n9F/g==,type:str]
    AUTH_PASSWORD: ENC[AES256_GCM,data:yN3ljIXk,iv:867cs/Oy0WmihyU87eMs9HUYdEQs7JYpW43Gn8xK7X4=,tag:4tMNT3U61JlXwBSCG7etLw==,type:str]
    AUTH_USERNAME: ENC[AES256_GCM,data:KAZf+r3mEg==,iv:4rDH4tjt7hw0e0MFpYyxqxxFVuT43vpA6EV3wSVrVTE=,tag:oFdLcZgyBM2KRlxrShfmjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qd2k83kj5ket4qp63rfa456pt5amx5j58sx0dk204crfsmjqvpks4jucs2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNekxTQ2ViSzJLZ1NKd3BH
            Uml5am90QmZ1WnRHVzlEMTJ1SVl0dUhjRWk0CmJwaHZEVXRCSitWSElSYjdJT2hZ
            QlB3UmR1R0tEV1JETjZsdURWd0JDN28KLS0tIDlVZ2wydWZ2R25VQ1BLRVZtS0JX
            NExiZE1BcGNGY3RuWk41eWt6UjIwaWcKpJjcWyAO9k53m73KbB9geeZoXw105a/U
            hXJy+82qHd5s4TL2OlkJ8roB5r4jPr/2ApUmVNrqB978ps/wjiNo5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-07T16:02:54Z"
    mac: ENC[AES256_GCM,data:nyPhwZkk9XWs9nPYLab0cUvTmOWXxHBj2wpl1PAa9VuKCSQHp+eRkt3iDkvnBY5wTga7BUkj2Gnn2SOzgM5FNNY3Wv7wKxXheUW7LrZ3/TOfUnAFDGT7iwdH/wSMyAbayYhWqKQhZs+jmYzQ6/3AYb52DW9wDvB1hU9KZCDn/3U=,iv:R8tYyeqKJmiECIhb+j/1ozZSBR68VwRAqzN8qs+mChA=,tag:dCGqFQIhvirEw+ScSYw+GQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
