apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-apikey
    namespace: default
type: Opaque
data:
    APIKEY: ENC[AES256_GCM,data:EvBBZ4JFIURa0kFKAbMOmC+4pa37LkgsbkrbJpSIjb+qPEJttKZ9n10XgrI=,iv:8bx2Vno6O8JzUQITRjEoS6yHU/NFmRFQx0cWNSlvAbQ=,tag:EXHSet2pWfGTDakmvOMuSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19jc9zp5pc7me0wkx28kc2ypr9qh6t9zphn3fdk63ae9dz9a2h5gsh4w866
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4L25WTU1wN2YxU0V5MG1m
            dHJtZkZvTENqUk1ndmozaWIwRGNFZFhGSFJRCnJIY0VsTlNkRnp2bEd3Y0RlRDdG
            TDlKT3B2QTdxa2lVVDRhb1VGU2xSYVUKLS0tIHVzRFR4OVYvVTdFcS9KVkxucytr
            VUxETUthYmh4b2QycnU5T0hKVmJlQ28Ks7nUV0RyfKJozVZS5TuyD5+KCU59dAFv
            Uu2zOoWf9ih0Mi85pNeFeZSIfppeZADBXbJJ7XtxGAIp5jzY4m5Ipg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-03T04:28:40Z"
    mac: ENC[AES256_GCM,data:zX4aVTaQ/uc+z9DhaQGPk3rlhPG1oxrqnjlZ4RZlhwCruk0tm/ik+E9PqNEo6WgDcRCWCVw/tBjF8m08y+v9wQBlvYs1AQHGbJIRHHEKt+Qi+TJRjj5Vfut6eD9Usk305aZGjdVqMY64/HGg2GWGFF2k12EAyX9Ilqv4O/+zI0M=,iv:+ZwFJYgJLxlLd2BwK3LFLG/UZVQRH18cQ56v08axZyY=,tag:OsffKFUzRPPIMzUVO5dSOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
