apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-apikey
    namespace: default
type: Opaque
data:
    APIKEY: ENC[AES256_GCM,data:ZgQj,iv:wMIooQ1lXb6+0N5PpvqG1mHJ1o1LRyeKpZ8PMLAIocM=,tag:gR3/3py9ZbnY336mrQMbUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19jc9zp5pc7me0wkx28kc2ypr9qh6t9zphn3fdk63ae9dz9a2h5gsh4w866
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4L25WTU1wN2YxU0V5MG1m
            dHJtZkZvTENqUk1ndmozaWIwRGNFZFhGSFJRCnJIY0VsTlNkRnp2bEd3Y0RlRDdG
            TDlKT3B2QTdxa2lVVDRhb1VGU2xSYVUKLS0tIHVzRFR4OVYvVTdFcS9KVkxucytr
            VUxETUthYmh4b2QycnU5T0hKVmJlQ28Ks7nUV0RyfKJozVZS5TuyD5+KCU59dAFv
            Uu2zOoWf9ih0Mi85pNeFeZSIfppeZADBXbJJ7XtxGAIp5jzY4m5Ipg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-03T03:59:16Z"
    mac: ENC[AES256_GCM,data:2l7Erd1H+mp+zQk6cmucGsZO70r1iTj0guC4uou80ABamgtWy6113J1sbMo2MAMfMWuyRWj5mRlGTvKYugmn0NPcF5wz0ka0h+Oc1uSaevoIcI/mJ7Cdrfzj8q3rboFltS9JPPJRkAXQv076/GP4iINyfXlJfvBEFWOm+bEl1Q0=,iv:jwTVeopvPXJ9+2KGfGKO+Gs+3ILcUVm1nfggz1c+IrA=,tag:Xn+KoMT/CAc7A+5qRE+YrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
