apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-apikey
    namespace: default
type: Opaque
data:
    APIKEY: ENC[AES256_GCM,data:ZnaV,iv:uXrVDLikG7MeHFKaJPFKKLX5DRn5jPzUC8C0rUzryyE=,tag:3Gzw2i7fat9zNmkufCZ40g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qd2k83kj5ket4qp63rfa456pt5amx5j58sx0dk204crfsmjqvpks4jucs2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNekxTQ2ViSzJLZ1NKd3BH
            Uml5am90QmZ1WnRHVzlEMTJ1SVl0dUhjRWk0CmJwaHZEVXRCSitWSElSYjdJT2hZ
            QlB3UmR1R0tEV1JETjZsdURWd0JDN28KLS0tIDlVZ2wydWZ2R25VQ1BLRVZtS0JX
            NExiZE1BcGNGY3RuWk41eWt6UjIwaWcKpJjcWyAO9k53m73KbB9geeZoXw105a/U
            hXJy+82qHd5s4TL2OlkJ8roB5r4jPr/2ApUmVNrqB978ps/wjiNo5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-22T03:47:29Z"
    mac: ENC[AES256_GCM,data:2U4oolBuAhnZ0PTs56PVuQkvoGI0gGXC/QZd0Eenm0AIPKoIdT5vJej6bsSmbwmmgaJF7GoAJKoF8laWkhPn9qnMyWYjcnk2DHfK9kh1za08QAupCQCxEFiacKrSQV6FaXOPblU+9HQ33VtJJHb7fsGntx5pxWc+QdQ8OkcdAyY=,iv:xFNY9aDaz4z1AImhb15RJuZa0FWkAq6ae+lbKAvLQ7Y=,tag:WK3/RvIqHqy9KdddW9fLJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
