---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rocket-chat
  namespace: default
spec:
  chart:
    spec:
      chart: rocketchat
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rocket-chat
        namespace: flux-system
      version: 6.23.2
  interval: 24h0m0s
  releaseName: rocket-chat
  targetNamespace: default
  values:
    existingMongodbSecret: mongodb-secret
    host: &host chat.internal.${SECRET_DOMAIN}
    persistence:
      enabled: true
      storageClass: nfs-csi
      size: 8Gi
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      tls:
        - secretName: rocket-tls
          hosts:
            - *host
    mongodb:
      persistence:
        storageClass: nfs-csi
        size: 8Gi
      auth:
        usernames: [ rocketchat ]
        passwords: [ ]
        databases: [ rocketchat ]
        existingSecret: mongodb-secret
