---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  chart:
    spec:
      chart: istiod
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  dependsOn:
    - name: istio-base
      namespace: istio-system
  interval: 6h0m0s
  releaseName: istiod
  targetNamespace: istio-system
  values:
#    profile: default
    base:
      enableIstioConfigCRDs: true
    experimental:
      stableValidationPolicy: false
    gateways:
      seccompProfile: { }
      securityContext: { }
    global:
      autoscalingv2API: true
      caAddress: ""
      caName: ""
      certSigners: [ ]
      configCluster: false
      configValidation: true
      defaultPodDisruptionBudget:
        enabled: true
      defaultResources:
        requests:
          cpu: 10m
      externalIstiod: false
      hub: docker.io/istio
      imagePullPolicy: ""
      imagePullSecrets: [ ]
      istioNamespace: istio-system
      istiod:
        enableAnalysis: false
      logAsJson: false
      logging:
        level: default:info
      meshID: ""
      meshNetworks: { }
      mountMtlsCerts: false
      multiCluster:
        clusterName: ""
        enabled: false
      network: ""
      omitSidecarInjectorConfigMap: false
      operatorManageWebhooks: false
      pilotCertProvider: istiod
      priorityClassName: ""
      proxy:
        autoInject: enabled
        clusterDomain: cluster.local
        componentLogLevel: misc:error
        enableCoreDump: false
        excludeIPRanges: ""
        excludeInboundPorts: ""
        excludeOutboundPorts: ""
        image: proxyv2
        includeIPRanges: '*'
        includeInboundPorts: '*'
        includeOutboundPorts: ""
        logLevel: warning
        outlierLogPath: ""
        privileged: false
        readinessFailureThreshold: 4
        readinessInitialDelaySeconds: 0
        readinessPeriodSeconds: 15
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        startupProbe:
          enabled: true
          failureThreshold: 600
        statusPort: 15020
        tracer: none
      proxy_init:
        image: proxyv2
      remotePilotAddress: ""
      sds:
        token:
          aud: istio-ca
      sts:
        servicePort: 0
      tag: 1.23.1
      variant: ""
    istio_cni:
      chained: true
      provider: default
    istiodRemote:
      injectionCABundle: ""
      injectionPath: /inject
      injectionURL: ""
    # https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig
    meshConfig:
      enablePrometheusMerge: false
      enableTracing: true
      ingressClass: istio-ingress
      defaultProviders:
        tracing: [otel-tracing]
        metrics: [prometheus]
      defaultConfig:
        proxyMetadata:
          ISTIO_META_DNS_CAPTURE: "true"
        tracing:
          sampling: 100.0
        tracingServiceName: CANONICAL_NAME_ONLY
      accessLogFile: /dev/stdout
      extensionProviders:
        - name: otel-tracing
          opentelemetry:
            port: 4317
            service: istio-collector-collector.istio-system.svc.cluster.local
            resource_detectors:
              environment: {}
    ownerName: ""
    pilot:
      affinity: { }
      autoscaleBehavior: { }
      autoscaleEnabled: false
      autoscaleMax: 5
      autoscaleMin: 1
      cni:
        enabled: false
        provider: default
      configMap: true
      cpu:
        targetAverageUtilization: 80
      deploymentLabels: { }
      env: { }
      extraContainerArgs: [ ]
      hub: ""
      image: pilot
      ipFamilies: [ ]
      ipFamilyPolicy: ""
      jwksResolverExtraRootCA: ""
      keepaliveMaxServerConnectionAge: 30m
      memory: { }
      nodeSelector: { }
      podAnnotations: { }
      podLabels: { }
      replicaCount: 1
      resources:
        requests:
          cpu: 500m
          memory: 2048Mi
      rollingMaxSurge: 100%
      rollingMaxUnavailable: 25%
      seccompProfile: { }
      serviceAccountAnnotations: { }
      serviceAnnotations: { }
      tag: ""
      taint:
        enabled: false
        namespace: ""
      tolerations: [ ]
      topologySpreadConstraints: [ ]
      traceSampling: 1
      trustedZtunnelNamespace: ""
      variant: ""
      volumeMounts: [ ]
      volumes: [ ]
    revision: ""
    revisionTags: [ ]
    sidecarInjectorWebhook:
      alwaysInjectSelector: [ ]
      defaultTemplates: [ ]
      enableNamespacesByDefault: false
      injectedAnnotations: { }
      neverInjectSelector: [ ]
      reinvocationPolicy: Never
      rewriteAppHTTPProbe: true
      templates: { }
    telemetry:
      enabled: true
      v2:
        enabled: true
        prometheus:
          enabled: true
        stackdriver:
          enabled: false
