apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: istio-collector
  namespace: istio-system
spec:
  mode: deployment
  config: |
    receivers:
      opencensus:
        endpoint: 0.0.0.0:55678
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
    exporters:
      otlp/uptrace:
        endpoint: my-uptrace.observability.svc.cluster.local:14317
        tls:
          insecure: true
        sending_queue:
          enabled: true
        retry_on_failure:
          enabled: true
        headers:
          uptrace-dsn: 'http://project2_secret_token@localhost:14318?grpc=14317'
    extensions:
      health_check:
    service:
      extensions:
      - health_check
      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/uptrace]
        traces:
          receivers:
          - otlp
          - opencensus
          exporters:
          - logging
          - otlp/uptrace
