---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cni
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  dependsOn:
  - name: istiod
    namespace: flux-system
  interval: 6h0m0s
  releaseName: istio-cni
  targetNamespace: flux-system
  values:
    profile: ambient
