apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: istio-collector
  namespace: istio-system
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      hostmetrics:
        scrapers:
          cpu:
          disk:
          filesystem:
          load:
          memory:
          network:
          paging:
    processors:
      batch:
      resourcedetection:
        detectors: [env, system]
      cumulativetodelta:
    exporters:
      otlp/uptrace:
        endpoint: my-uptrace.observability.svc.cluster.local:14317
        tls:
          insecure: true
        sending_queue:
          enabled: true
        retry_on_failure:
          enabled: true
        headers:
          uptrace-dsn: 'http://istio_secret_token@localhost:14318?grpc=14317'
    extensions:
      health_check:
    service:
      extensions:
      - health_check
      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/uptrace]
        traces:
          receivers:
            - otlp
          exporters:
            - otlp/uptrace
        metrics:
          receivers: [otlp]
          processors: [cumulativetodelta, batch]
          exporters: [otlp/uptrace]
