apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali
  namespace: istio-system
spec:
  interval: 1h
  chart:
    spec:
      chart: kiali-operator
      sourceRef:
        name: kiali
        kind: HelmRepository
        namespace: flux-system
  values:
    cr:
      create: true
      namespace: istio-system
      spec:
        istio_labels:
          app_label_name: "app.kubernetes.io/name"
          version_label_name: "app.kubernetes.io/version"
        auth:
          strategy: anonymous
        deployment:
          accessible_namespaces: [ "**" ]
          view_only_mode: false
          ingress:
            enabled: true
            class_name: internal
            override_yaml:
              metadata:
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt-production
              spec:
                tls:
                  - hosts:
                    - kiali.internal.${SECRET_DOMAIN}
                    secretName: kiali-tls
                rules:
                  - host: kiali.internal.${SECRET_DOMAIN}
                    http:
                      paths:
                        - path: /
                          pathType: Prefix
                          backend:
                            service:
                              name: kiali
                              port:
                                number: 20001
        istio_namespace: istio-system
        external_services:
          custom_dashboards:
            enabled: true
          istio:
            root_namespace: istio-system
          grafana:
            enabled: true
            url: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:3000
            in_cluster_url: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:3000
          prometheus:
            enabled: true
            in_cluster_url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
            url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          tracing:
            enabled: true
            url: http://jaeger-jaeger-operator-jaeger-query.monitoring.svc.cluster.local:16685/jaeger
            in_cluster_url: http://jaeger-jaeger-operator-jaeger-query.monitoring.svc.cluster.local:16685/jaeger
            use_grpc: true
