apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: otel-demo
  namespace: istio-system
spec:
  tracing:
    - providers:
        - name: otel-tracing
          opentelemetry:
            port: 4317
            service: istio-collector-collector.istio-system.svc.cluster.local
            resource_detectors:
              environment: {}
      randomSamplingPercentage: 100
