apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: otel-demo
  namespace: istio-system
spec:
  tracing:
    - providers:
        - name: otel-tracing
      randomSamplingPercentage: 100
      match:
        mode: CLIENT_AND_SERVER
  selector:
    matchLabels:
      app: radarr
