---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: autobrr
  namespace: default
spec:
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.4.0
  interval: 6h0m0s
  releaseName: autobrr
  targetNamespace: default
  values:
    controllers:
      main:
        containers:
          autobrr:
            env:
              TZ: America/Chicago
            image:
              repository: ghcr.io/autobrr/autobrr
              tag: v1.47.0
            securityContext:
              runAsGroup: 1000
              runAsUser: 1000
        enabled: true
        type: deployment
    global:
      fullnameOverride: autobrr
      labels:
        app: autobrr
    ingress:
      autobrr:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        className: internal
        enabled: true
        hosts:
        - host: autobrr.internal.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: autobrr
        tls:
        - hosts: autobrr.internal.${SECRET_DOMAIN}
          secretName: autobrr-tls
    persistence:
      config:
        enabled: true
        size: 1Gi
        storageClass: nfs-client-ssd
    service:
      autobrr:
        controller: main
        enabled: true
        ports:
          http:
            appProtocol: http
            enabled: true
            port: 7474
