apiVersion: v1
kind: ConfigMap
metadata:
  name: glances-config
  namespace: default
data:
  glance.yml: |
    pages:
      - name: Home
        columns:
          - size: small
            widgets:
              - type: calendar

          - size: full
            widgets:
              - type: search
                search-engine: duckduckgo
                bangs:
                  - title: YouTube
                    shortcut: "!yt"
                    url: https://www.youtube.com/results?search_query={QUERY}
              - type: videos
                channels:
                  - UC1D3yD4wlPMico0dss264XA # NileBlue
                  - UC7_YxT-KID8kRbqZo7MyscQ # Markiplier
              - type: reddit
                subreddit: selfhosted

          - size: small
            widgets:
              - type: weather
                location: ${SECRET_LOCATION}

      - name: Grafana
        columns:
          - size: full
            widgets:
              - type: iframe
                source: http://grafana.internal.stiforr.com:3000/d/WURH98Y4k/media-dashboard?from=2024-11-12T20:12:20.469Z&to=2024-11-13T20:12:20.469Z&timezone=browser&var-DS_PROMETHEUS=prometheus&var-prowlarr_instance=$__all&var-sabnzbd_instance=$__all&var-radarr_instance=$__all&var-sonarr_instance=$__all&var-lidarr_instance=$__all&var-readarr_instance=$__all&var-bazarr_instance=$__all&refresh=30s
                height: 800
