apiVersion: v1
kind: ConfigMap
metadata:
  name: glances-config
  namespace: default
data:
  glance.yml: |
    pages:
      - name: Home
        columns:
          - size: small
            widgets:
              - type: calendar

          - size: full
            widgets:
              - type: search
                search-engine: duckduckgo
                bangs:
                  - title: YouTube
                    shortcut: "!yt"
                    url: https://www.youtube.com/results?search_query={QUERY}
              - type: videos
                channels:
                  - UC1D3yD4wlPMico0dss264XA # NileBlue
                  - UC7_YxT-KID8kRbqZo7MyscQ # Markiplier
              - type: reddit
                subreddit: selfhosted

          - size: small
            widgets:
              - type: weather
                location: ${SECRET_LOCATION}
