apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8s-gateway
  namespace: monitoring
spec:
  jobLabel: k8s-gateway
  selector:
    matchLabels:
      k8s-app: k8s-gateway
  namespaceSelector:
    matchNames:
      - network
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
      path: /metrics
