---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: mastodon
  namespace: default
spec:
  interval: 24h0m0s
  ref:
    branch: main
  url: https://github.com/mastodon/chart
