---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: monitoring
spec:
  chart:
    spec:
      chart: jaeger-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jaeger
        namespace: flux-system
  interval: 1h0m0s
  values:
    jaeger:
      create: true
      namespace: monitoring
    rbac:
      create: true
      pspEnabled: true
      clusterRole: true
