apiVersion: v1
kind: Secret
metadata:
    name: discord-token
    namespace: default
type: Opaque
stringData:
    TOKEN: ENC[AES256_GCM,data:xRfZ9DArcOun8Ay304qii57JZm6h9fYJ9nYZHVp2/nPN16zwo4sEAGXpHkIFG6ugWsBz/Be9/Ns9p9CaHHI7D8IuG/rfEmBh,iv:CE9rmnD3q2enIFPFSm6s0F5iiJ288JVTZQXlrQb/igo=,tag:5LsGoXyb29SrH1exWW2A2A==,type:str]
