---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: default
spec:
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.4.0
  interval: 6h0m0s
  releaseName: default
  targetNamespace: default
  values:
    # yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.2.0/charts/library/common/values.schema.json
    controllers:
      main:
        annotations: {}
        containers:
          main:
            env:
            - name: TZ
              value: "America/Chicago"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            image:
              repository: filebrowser/filebrowser
              tag: v2.31.1-s6
        enabled: true
        type: deployment
    global:
      fullnameOverride: filebrowser
    ingress:
      main:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        className: internal
        enabled: true
        hosts:
        - host: files.internal.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - files.internal.${SECRET_DOMAIN}
          secretName: files-tls
    persistence:
      config:
        accessMode: ReadWriteOnce
        enabled: true
        size: 1Gi
        type: persistentVolumeClaim
      database:
        accessMode: ReadWriteOnce
        enabled: true
        size: 2Gi
        type: persistentVolumeClaim
      srv:
        enabled: true
        existingClaim: media-pvc-ssd
    service:
      main:
        controller: main
        enabled: true
        ports:
          http:
            enabled: true
            port: 80
            targetPort: 80
    serviceAccount:
      create: true
    serviceMonitor:
      main:
        enabled: true
        serviceName: main
