apiVersion: v1
kind: Secret
metadata:
    name: authentik-config
    namespace: default
type: Opaque
data:
    #ENC[AES256_GCM,data:XXBIdyWHEtzHBrymDdBkmMwlBoQd0j3Vs4RFSul48m4=,iv:1+sv9I/MaNf8F9Z8cq0HUXBmaTHz9NGr0sNClveOYZQ=,tag:cZsChrXP5WYDAcfNKysUcA==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:+7Fb8oDvO9L2LyAfQyp4GxnlSpM7grtK8eVlZh4quhjNvpoSIe+LKaVg/kAvRhd5vYocl0O2kOyfLDcr1vH6ULs13D0=,iv:WNiwO8YvKv8YOsrOLqGLslUOHziAnIhEY1SgPzz6te0=,tag:5zDKlIgbM50kqJ3TKAd/pw==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:BKC3IEPHrp3UaChPmNYMJwl/DT4Teb6MUCaNIsaJ2TITrkxrQXcNBgSB6KqpN1Jzh0a/hKBVFlMv5HPEGVOCu5aYVOM=,iv:r2kXUo3kf0GSwQq1T/A5YT9Dz3FFVh5XB+z/Nh9aMhE=,tag:hK/acgdico0Cxsz5u8VwSA==,type:str]
    AUTHENTIK_REDIS__PASSWORD: ENC[AES256_GCM,data:v0JZ38qud5+2nL/iVC6ZHNQ9V9XjC0PGN0LHHy9f6luCGEyX9rEAk+P0o3WavgltDtkH4aozQ/Wv2TQU3pcxlhBUwJw=,iv:+/ZXWnhAuo8PLe2pPyDOVjuFu4Kw3fm5c2XfNqXBBXY=,tag:9amAsTfqKKafbwajy1zV8g==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:oHDHd5TYN/xLxS1tVySoBqPIYxsCrRdR4046SePwd3BX2rkyTsbcuIH+Ujr4lqtPwjdtAAK+492I2sj7Pijr4MZj+U8=,iv:UjiN22Se85iCSjbab7sjY45LLaVGxXdOfkd2wYdchSk=,tag:qEGksjNeo20CD4iCSUkTSA==,type:str]
