apiVersion: v1
kind: Secret
metadata:
    name: authentik-config
    namespace: default
type: Opaque
data:
    #ENC[AES256_GCM,data:XXBIdyWHEtzHBrymDdBkmMwlBoQd0j3Vs4RFSul48m4=,iv:1+sv9I/MaNf8F9Z8cq0HUXBmaTHz9NGr0sNClveOYZQ=,tag:cZsChrXP5WYDAcfNKysUcA==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:+7Fb8oDvO9L2LyAfQyp4GxnlSpM7grtK8eVlZh4quhjNvpoSIe+LKaVg/kAvRhd5vYocl0O2kOyfLDcr1vH6ULs13D0=,iv:WNiwO8YvKv8YOsrOLqGLslUOHziAnIhEY1SgPzz6te0=,tag:5zDKlIgbM50kqJ3TKAd/pw==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:FwT8REoxK64=,iv:cCMvMDm88+sAQiVmbkDsMsR9mvoOkkINmWDEFZIY7fM=,tag:6jBDjeHbDb/7GPrGxHp/Rw==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:b4JZCMLpnulcgOTpDLk9sQ==,iv:a8ZC0t4G1cLYDxDLZB9OyJhTCk3+QRqUMdhYGBLs3+g=,tag:JexRAZt0QB1asyOnBzXzeQ==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:BKC3IEPHrp3UaChPmNYMJwl/DT4Teb6MUCaNIsaJ2TITrkxrQXcNBgSB6KqpN1Jzh0a/hKBVFlMv5HPEGVOCu5aYVOM=,iv:r2kXUo3kf0GSwQq1T/A5YT9Dz3FFVh5XB+z/Nh9aMhE=,tag:hK/acgdico0Cxsz5u8VwSA==,type:str]
    AUTHENTIK_REDIS__PASSWORD: ENC[AES256_GCM,data:v0JZ38qud5+2nL/iVC6ZHNQ9V9XjC0PGN0LHHy9f6luCGEyX9rEAk+P0o3WavgltDtkH4aozQ/Wv2TQU3pcxlhBUwJw=,iv:+/ZXWnhAuo8PLe2pPyDOVjuFu4Kw3fm5c2XfNqXBBXY=,tag:9amAsTfqKKafbwajy1zV8g==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:oHDHd5TYN/xLxS1tVySoBqPIYxsCrRdR4046SePwd3BX2rkyTsbcuIH+Ujr4lqtPwjdtAAK+492I2sj7Pijr4MZj+U8=,iv:UjiN22Se85iCSjbab7sjY45LLaVGxXdOfkd2wYdchSk=,tag:qEGksjNeo20CD4iCSUkTSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19jc9zp5pc7me0wkx28kc2ypr9qh6t9zphn3fdk63ae9dz9a2h5gsh4w866
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0a0RyUmk3dzdiRThkeSt4
            WDFteWVhS0EwbnlCUEJkeXlRUTRzNndpbGhVCi8zT0xXaGJxTHBodFIwMWNFVjgr
            MndzWWVmTjFJOTdEUWFwT0hDSk9nZmMKLS0tIGwrQ3FCVzhZOTZNc1M3bno2S0xt
            TTByajNKSVY0cjlWZzd1TFkva3pwZWMKUHJMhK0K8ip1RWUBnZS82Vx3h9IOdeKs
            d3Ps1yVH5V9bzI0ctLIBnrahLciDYdsNRLI9FWNhTc0G993wGmXisQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-01T03:41:21Z"
    mac: ENC[AES256_GCM,data:YZrvcIDUOjW/F+4fNnEiSiZ4OcUwBhFLdVRsWrOpc7cqhkRMCjyoiHfEjM7QyLttfP1rOHjNHO25SJLI3w2kmkY/abrZQtrHVPexEfrluNmc6dajBXIzBKH3y5S/d0X041U95PI7ZSc0DPETLpCM6TkvY6s/t7ErzwClqCJ07vk=,iv:xBhD5bz1QVmpcEqIYI/3+0BuQ0RCQfGtefzRuxaA/F4=,tag:XHetBj2L0zGn7Hu4x2FJgQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
