apiVersion: v1
kind: Service
metadata:
  name: adguard
  namespace: default
spec:
  externalName: adguard.stiforr.com
  type: ExternalName
  ports:
    - port: 443
      name: https
      protocol: TCP
      appProtocol: https
