apiVersion: v1
kind: Service
metadata:
  name: adguard-proxy
  namespace: default
  labels:
    app: adguard-proxy
spec:
  externalName: adguard.stiforr.com
  type: ExternalName
  ports:
    - port: 443
      name: metrics
      protocol: TCP
      appProtocol: https
