apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: adguard
  namespace: default
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      honorLabels: true
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: adguard-proxy
