apiVersion: v1
kind: ConfigMap
metadata:
  name: mailu-config
  namespace: default
data:
  mailu-values.yaml: |
    domain: internal.${SECRET_DOMAIN}
    hostnames:
      - mail.internal.${SECRET_DOMAIN}
      - imap.internal.${SECRET_DOMAIN}
    initialAccount:
      domain: stiforr.internal.${SECRET_DOMAIN}
