apiVersion: v1
kind: Secret
metadata:
    name: mailu-secret
    namespace: default
type: Opaque
stringData:
    roundcube-password: ENC[AES256_GCM,data:3S+zafGNQT1QpGSFXTTAvH20efrFocLhNbUX0cEvADU=,iv:XnDjKHgSAc5HIbOmr61Dgq+gdz6ZL/U6cykJe03OO3g=,tag:yumEg6k+tFe0XsHiiANHtQ==,type:str]
    secret-key: ENC[AES256_GCM,data:TBLag4ymiYGqOlrNVG0ivfvwsYj8eGxV/qoUXXMLfoc=,iv:yqnxGO1tiM4/8gSJeZHv4jz0J34P5hfa/BRcILGrRjk=,tag:nazLtLjxhSXu9SMCtjBvRg==,type:str]
    user-password: ENC[AES256_GCM,data:PuvcDGGS6khI,iv:1bdEVBt5C7c4Y9Eh30AUmjHMF7xAlQ/OeaLKiI3rNic=,tag:FPBt/+Hf5DW1jWl2RIctGw==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:uujh32/U9seyAA+BmvIW6iB61l6sWiw/GZuUdez7sbQ=,iv:YtCephRPTjcWurQLMJhiMRG6Ew1r9w3YkU9DDt1EVYY=,tag:uE9ok3GGGsXA/MVZNtuPtA==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:rPG4PS5KBpczPvOrqR+Tg2qnQG3pkPnRwonwJyALBv0=,iv:e4+f4Gzgiji4KYwPdAsymlWgyGlHkC9B2keA9crxwPE=,tag:RTTkMBqOrzWhkQmcMO9dtw==,type:str]
    mariadb-password: ENC[AES256_GCM,data:daLKQD5s5Z9IMOHI81fWgJkPDZUE19C9y9gZGBWZYB0=,iv:8kj0AqBlos+0Xgnly/abNxjh/HXQuWnBa8MeY/jnV6U=,tag:MKkKjXRzQ4kMiCONbDqjRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qd2k83kj5ket4qp63rfa456pt5amx5j58sx0dk204crfsmjqvpks4jucs2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcVpHd0dqZUhWNzNzMUQr
            cTlHSThza3RWOUozNmo1OE9mV3NDZklxbkc4CkoxWEV6WnFZNm15c3U4cTR2STFN
            MldQdlZ4VS95Q3h4blh6K0cvWDlwM1UKLS0tIE1TVC9nbDNabm1Gd3JZZFlNa1pU
            R0E2QjFBRG90Ry9sOFAvSW1jSmhFd2cKsnyVZmejWVSRewJAdbj1RJw/my2zAQ8D
            33bxJ/SFIT0TIdKKyQN2A4nBagpO40JP6wXiH8d19fKAd07i4J3MUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T16:27:10Z"
    mac: ENC[AES256_GCM,data:Z/S21wA6Ro/eVHznJ+gNefuHy0pMsGlXEyKPrTzlBcWqPW8Jk/lRUfMEJU/fkiSmT9GnTqxdm7j/J2xRUm7gWsjMb7jmYnXvlw+49HxKiZFoZy79k+/3W0XJ6XCwthCYRRSELaYR2RNZqS7TTolgiTFWGUQQ2jrjFs9tLxSy8LQ=,iv:AL5aQcSrX0I41DaUZJJgR4LB7ZmXxraFrymIXjsd9B4=,tag:sRv7oj3emDP91BGVAxpRiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
