---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mailu
  namespace: default
spec:
  chart:
    spec:
      chart: mailu
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: mailu
        namespace: flux-system
      version: 2.1.1
  interval: 24h0m0s
  install:
    remediation:
      remediateLastFailure: true
      retries: 5
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 5
  releaseName: mailu
  targetNamespace: default
  values:
    admin:
      enabled: true
      persistence:
        accessModes:
          - ReadWriteOnce
        annotations: { }
        claimNameOverride: ""
        size: 1Gi
        storageClass: openebs-hostpath
      resources:
        limits:
          cpu: 250m
          memory: 250Mi
        requests:
          cpu: 125m
          memory: 125Mi
      revisionHistoryLimit: 3
      updateStrategy:
        type: RollingUpdate
      uri: /admin
    api:
      enabled: false
      existingSecret: ""
      existingSecretTokenKey: api-token
      token: ""
      webPath: /api
    authRequireTokens: false
    clamav:
      enabled: false
    customization:
      logoBackground: ""
      logoUrl: ""
      siteName: Mailu
      website: https://mailu.io
    dmarc:
      rua: ""
      ruf: ""
    domain: internal.${SECRET_DOMAIN}
    dovecot:
      enabled: true
    existingSecret: mailu-secret
    externalDatabase:
      enabled: false
    externalRedis:
      enabled: false
    fetchmail:
      enabled: false
    front:
      hostPort:
        enabled: true
      kind: Deployment
      logLevel: ""
      replicaCount: 1
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 250m
          memory: 250Mi
      revisionHistoryLimit: 3
      service:
        annotations: { }
      updateStrategy:
        type: RollingUpdate
    fullnameOverride: mailu
    global:
      database:
        roundcube:
          database: roundcube
          existingSecret: mailu-secret
          existingSecretPasswordKey: roundcube-password
          username: roundcube
      storageClass: nfs-client-ssd
    hostnames:
      - mail.internal.${SECRET_DOMAIN}
      - imap.internal.${SECRET_DOMAIN}
    imageRegistry: ghcr.io
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      enabled: true
      ingressClassName: cilium
      path: /
      pathType: ImplementationSpecific
      proxyProtocol:
        imap: false
        imaps: false
        manageSieve: false
        pop3: false
        pop3s: false
        smtp: false
        smtps: false
        submission: false
      realIpFrom: ""
      realIpHeader: X-Forwarded-For
      tls: true
      tlsFlavorOverride: ""
    initialAccount:
      domain: stiforr.internal.${SECRET_DOMAIN}
      enabled: true
      existingSecret: mailu-secret
      existingSecretPasswordKey: user-password
      mode: ifmissing
      username: stiforr
    limits:
      authRatelimit:
        exemption: ""
        exemptionLength: 86400
        ip: 60/hour
        ipv4Mask: 24
        ipv6Mask: 56
        user: 100/day
      messageRatelimit:
        exemption: ""
        value: 200/day
      messageSizeLimitInMegabytes: 50
    logLevel: WARNING
    mailuVersion: ""
    mariadb:
      architecture: standalone
      auth:
        database: mailu
        existingSecret: mailu-secret
        username: mailu
      enabled: true
      initdbScripts:
        create_roundcube_database.sh: |
          #!/bin/bash
          # set -o errexit
          # set -o nounset
          # set -o pipefail
          echo "Checking for DB initialisation"
          if [ -S /opt/bitnami/mariadb/tmp/mysql.sock ]; then
            echo "Running DB initialisation..."
            /opt/bitnami/mariadb/bin/mysql --user="root" --password="${MARIADB_ROOT_PASSWORD}" <<SQL
            --
            -- Initialisation script for roundcube database
            --
            CREATE DATABASE IF NOT EXISTS ${ROUNDCUBE_DB_NAME};
            GRANT ALL PRIVILEGES ON ${ROUNDCUBE_DB_NAME}.* TO '${ROUNDCUBE_DB_USER}'@'%' IDENTIFIED BY '${ROUNDCUBE_DB_PW}';
            FLUSH PRIVILEGES;
          SQL
            echo "DB initialisation complete"
          else
            echo "Not running initialisation, exiting..."
          fi
      primary:
        extraEnvVars: |
          - name: ROUNDCUBE_DB_PW
            valueFrom:
              secretKeyRef:
                name: {{ include "mailu.database.roundcube.secretName" . }}
                key: {{ include "mailu.database.roundcube.secretKey" . }}
          - name: ROUNDCUBE_DB_NAME
            value: {{ include "mailu.database.roundcube.name" . }}
          - name: ROUNDCUBE_DB_USER
            value: {{ include "mailu.database.roundcube.username" . }}
        persistence:
          accessMode: ReadWriteOnce
          enabled: false
          size: 8Gi
          storageClass: openebs-hostpath
    oletools:
      enabled: false
    permanentSessionLifetime: 2592000
    persistence:
      accessModes:
        - ReadWriteOnce
      single_pvc: true
      size: 10Gi
      storageClass: nfs-client-ssd
    postfix:
      logLevel: ""
      persistence:
        accessModes:
          - ReadWriteOnce
        size: 1Gi
        storageClass: openebs-hostpath
      resources:
        limits: { }
        requests: { }
    postgresql:
      enabled: false
    postmaster: postmaster
    proxyAuth:
      create: "false"
      header: X-Auth-Email
      whitelist: ""
    recipientDelimiter: +
    redis:
      architecture: standalone
      auth:
        enabled: false
      enabled: true
      master:
        count: 1
        enabled: true
        persistence:
          accessModes:
            - ReadWriteOnce
          enabled: true
          size: 8Gi
      replica:
        count: 0
    rspamd:
      enabled: false
    sessionCookieSecure: true
    sessionTimeout: 3600
    subnet: 10.69.0.0/16
    tika:
      enabled: false
    timezone: America/Chicago
    webdav:
      enabled: false
    webmail:
      enabled: true
      image:
        repository: mailu/webmail
        tag: 2024.06.24
        pullPolicy: IfNotPresent
      logLevel: ""
      persistence:
        accessModes:
          - ReadWriteOnce
        annotations: { }
        claimNameOverride: ""
        size: 2Gi
        storageClass: openebs-hostpath
      resources:
        limits: { }
        requests: { }
      roundcubePlugins:
        - archive
        - zipdownload
        - markasjunk
        - managesieve
        - enigma
        - carddav
        - mailu
      type: roundcube
      uri: /webmail
    welcomeMessage:
      body: Welcome to Mailu, your new email service. Please change your password
        and update your profile.
      enabled: true
      subject: Welcome to Mailu
    wildcardSenders:
      - notif.internal.${SECRET_DOMAIN}
