---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: default
spec:
  chart:
    spec:
      chart: sonarr
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 6h
  install:
    remediation:
      retries: 30
  upgrade:
    remediation:
      retries: 30
  values:
    global:
      labels:
        app: sonarr
    env:
      TZ: America/Chicago
      PUID: 568
      PGID: 568
    image:
      repository: linuxserver/sonarr
      tag: 4.0.9
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/enable: "true"
          hajimari.io/group: Media
          hajimari.io/icon: mdi:television-classic
          nginx.ingress.kubernetes.io/service-upstream: "false"
        hosts:
          - host: &host sonarr.internal.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: sonarr-tls
    persistence:
      config:
        enabled: true
        storageClass: openebs-hostpath
      vids:
        enabled: true
        mountPath: /data
        storageClass: openebs-hostpath
        accessMode: ReadWriteMany
        existingClaim: media-pvc-ssd
        size: 250Gi
    metrics:
      enabled: true
      exporter:
        image:
          repository: ghcr.io/onedr0p/exportarr
          tag: v2.0.1
          pullPolicy: IfNotPresent
        env:
          additionalMetrics: true
          unknownQueueItems: true
