apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ZCwxSb24Q8BesBlgQmiZYQKeWsriVpQlbx35Aqt0aY9ZqQvB,iv:d/UaM0OY2kz0lAJ8e/Hq/WFLaH3edHzQuMVpMMvA9Pg=,tag:hMn5aB44PFIBlmiM5jajew==,type:str]
    credentials.json: ENC[AES256_GCM,data:Vq6cy5sbovunHAFPD0fyp1LIQB6qINey7LKr/kFC7hb1cAJ0xSGKzKZyXxgQCW8yxWNUGkZ2xVqr2n4ayykXl+1J8I3iQ6MRvz8l47aiB2mcSaWXHgnLHNFL4U65YC2oflsp/TUPJOmA317SeSzFNrZ4acBiUat/DVFXLZEMiATCWhPRH7wZpwfjzGHVASIuGKK5fbYY0dBrGwZexHzATZveLeKNvJZZsl7Fhyh+ng==,iv:Rwaso4VYdvexLOT45pjobj8sf5iySmyTkECdEGedOm0=,tag:AOboirmyszcJE5P6rwKK9g==,type:str]
