apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:FbGrEKhe9/2DgfFe4W7ZAiT9VL42m55O8QomsCMP5zPInXzS,iv:l8qnIEm+UIQr17bgzYm31OvHD4Kak3Zg8YgAKVZtMmQ=,tag:AfeRvd5HxTUyYpkOt7jV3A==,type:str]
    credentials.json: ENC[AES256_GCM,data:YtR2m30wyIlzZHymYPS7+wJQoVq0I40Ex1cZlyB95vFSVPFaQWnnbPoDvegaHrj8dixwc9g+hDZD6CmqTJ21a8+NZMx7A3Bv0g3V8+yPVCILOFa0c0oEq7ZmCTbubejjA5ZLkzxq9A/lx3em9T9YnBN5e4W1obHMFUhBVp3m/lFxG4D5YpLeMr1D0lfNLUbYtsfrv+TdWVJm+3r7nQYPLgsk/Pacha8mYSPGBoGwXg==,iv:JymKwyi2vDnfgVumV/phLQj2BnLP2k69QeT4pn5VmbY=,tag:agKLiv8twTnA1Pi+oczwTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qd2k83kj5ket4qp63rfa456pt5amx5j58sx0dk204crfsmjqvpks4jucs2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZXJFeW1OVjVaUEtNVnNw
            eW5SbHRBems3M01vNUI1TTZUQW1TdGxrYUQwCmJNT3BtT3VEMnRyOXFXOGRDbHdr
            azh1ekIvY0ZCNVVISkVyeFpKWkZtYzAKLS0tIHpEM2JhSndkemZTNXdaOU9icGIw
            ZVVoeVhJYjAxTnBrQmxXSEo1eHlQSGMKa2aLT3NtrJ0BQf4q0FzneE39bJmAYoxb
            rPXUi2BdYu2sFqIYoucGKjDtzHLPEaWQQmsOe6T0A16zBm8EucWl/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-17T18:34:12Z"
    mac: ENC[AES256_GCM,data:pG/L47Rf80YXVw3g47/TF18j8JGJyj0dPem6qOvA8My2mXP6tNYm5mVOWemG3vmfa7vfWvEC/fpZnSuYDoxgjU9P+Tt66Gizz/NOTtL0nRLpA/+tZ6574SaHYzgdZ0s5DawrubI28jaXGWgLdlCn0XY1hlgkuHqoNTsONEr5Okk=,iv:hXZoUyN3+u9MzQOnVJ45XOegyyHHoykKdXQrSzjhMvo=,tag:rP2Adp1U4bv8z6xVPSwaow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
