apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:rtLeq8PSiOZHjcMs4oXqeQhtRceL9l4WwQn/HtZMlnWAsYFz,iv:XToTwMe3qp0LkNc3y8K+hvDtK76SbXcA0EG/5wV8bac=,tag:j9lPSktRBfjHRybHtw11ZA==,type:str]
    credentials.json: ENC[AES256_GCM,data:8ggj5yYh+r45wG/1oTpthDtpJ9odrBefHcs2v9xthetVbtOfYwtNBroqpZV3Zgz4Y242VOKlukPjoI5uCMCn0bOq9+oTfP56VgYtnhrZRcluCb2QtU+PW+owQ7Ty/vVwF1XKzDpfv+Zhf5ot5DXj0bXFNZATzNOrzFjA1mYoamzcAPGowv9ZJ1hxQoYERPcj+Iv7u7dRkcyEd/QVpMtqmXtjtuGIMkoAzcsMjSUqOw==,iv:e5mF2pL9RaY7NALPMEqHVZUdlwMtdKLOCIsk+nEAhBk=,tag:jXbgfff9ZOliYqTqOtdf5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qd2k83kj5ket4qp63rfa456pt5amx5j58sx0dk204crfsmjqvpks4jucs2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaEt0aHlIaWppaGw1L1Fu
            UUZSWEtCRDM5SUNIb1hLNG1JdTQ3M3UrVWpFCjhnK2hKMXNLeThmdHBUZWtIbjJs
            OXJDZldPWFoxTzJOTnFRMnJGNWJTclkKLS0tIE9CQUhJdkVua1JDZUM4MDV6SU5p
            MFdLWnlmQ1NlM2ZHdS9mZzJjQXIvK0EKyphyCCAsZ5S5FhzWPAsVZty1Mr5n47MV
            1uc+v1O6osvlSNko5ysbV+ziSMsRq4XxoYIbEY2HoR61m293cTzLTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-19T23:42:55Z"
    mac: ENC[AES256_GCM,data:hAXbEZl9oY4cKAoWgKa8Z2ke1TjilZJE9aw0vOVyVYWUYdRdUTHM8LnxbSjsxDx0ZSCa5JV+msW0XsNwo+hkiT9CgVB2Myl0u3V4l10UYFLlC9fEFZhMaV3v/sjHvbRA+84xbfHB+FQBViN8aM/ipeU0kADLHvbpV2zfIkdokbs=,iv:LFxC9HTMljTb8PVk9fFdz6Wc5VfFdHENGTP00SMxW2M=,tag:KEnwbffKHQzopCWK7+/uKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
