---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: forgejo
  namespace: flux-system
spec:
  interval: 24h0m0s
  provider: generic
  ref:
    tag: 10.1.2
  url: oci://code.forgejo.org/forgejo-helm/forgejo
