---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: prowlarr
  namespace: flux-system
spec:
  interval: 6h0m0s
  provider: generic
  ref:
    tag: 18.5.4
  url: oci://tccr.io/truecharts/prowlarr
