---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: tautulli
  namespace: flux-system
spec:
  interval: 6h0m0s
  provider: generic
  ref:
    tag: 20.2.0
  url: oci://tccr.io/truecharts/tautulli
