---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  chart:
    spec:
      chart: promtail
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 6h0m0s
  releaseName: promtail
  targetNamespace: monitoring
  values:
    fullnameOverride: promtail
    daemonset:
      enabled: true
    service:
      enabled: true
    configMap:
      enabled: true
    image:
      registry: docker.io
      repository: grafana/promtail
    serviceMonitor:
      enabled: true
      scrapeTimeout: 10s
    config:
      clients:
        - url: http://loki-gateway/loki/api/v1/push
      snippets:
        extraScrapeConfigs: |
          - job_name: nginx
            static_configs:
            - targets:
                - localhost
              labels:
                job: nginx
                host: nginx01
                agent: promtail
                __path__: /var/log/nginx/*log
    sidecar:
      configReloader:
        enabled: true
