---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
  namespace: default
spec:
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.4.0
  interval: 12h0m0s
  releaseName: bazarr
  targetNamespace: default
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        enabled: true
        type: deployment
        containers:
          main:
            env:
              - name: TZ
                value: America/Chicago
              - name: PUID
                value: 1000
              - name: PGID
                value: 1000
              - name: ENABLE_ADDITIONAL_METRICS
                value: "true"
            image:
              repository: linuxserver/bazarr
              tag: 1.4.5
            nameOverride: bazarr
          exportarr:
            enabled: true
            image:
              repository: ghcr.io/onedr0p/exportarr
              tag: v2.0.1
            args:
              - bazarr
            env:
              API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: bazarr-apikey
                    key: API_KEY
              URL: http://bazarr:6767
              PORT: 6768
              FORM_AUTH: false
            envFrom:
              - secret: bazarr-apikey
    global:
      fullnameOverride: bazarr
      labels:
        app: bazarr
    ingress:
      main:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/enable-opentelemetry: "true"
          nginx.ingress.kubernetes.io/otel-service-name: bazarr
          nginx.ingress.kubernetes.io/service-upstream: "true"
        className: internal
        enabled: true
        hosts:
          - host: bazarr.internal.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
        tls:
          - hosts:
              - bazarr.internal.${SECRET_DOMAIN}
            secretName: bazarr-tls
    persistence:
      config:
        accessMode: ReadWriteOnce
        enabled: true
        size: 1Gi
        storageClass: nfs-client-ssd
        type: persistentVolumeClaim
      data:
        enabled: true
        existingClaim: media-pvc-ssd
    service:
      main:
        controller: main
        enabled: true
        primary: true
        ports:
          http:
            enabled: true
            primary: true
            appProtocol: http
            port: 6767
            protocol: HTTP
      exportarr:
        enabled: true
        primary: false
        controller: main
        ports:
          metrics:
            enabled: true
            primary: false
            port: 6768
            protocol: HTTP
            appProtocol: http
    serviceAccount:
      create: true
    serviceMonitor:
      exportarr:
        enabled: true
        serviceName: bazarr-exportarr
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 4m
            scrapeTimeout: 90s
