apiVersion: v1
kind: Secret
metadata:
    name: bazarr-apikey
    namespace: default
type: Opaque
data:
    API_KEY: ENC[AES256_GCM,data:U4uGifhyKqq2x43nTFmmftABlCJ0Csd8X0bqUh5PuYjMQnbHdPZe79KORV8=,iv:oEZr6G2c7Cu67qF6fsaVRJ1jGcFT7mhdFJ4dGwF12uY=,tag:+igF5acDmjApt2zwD6teiQ==,type:str]
    AUTH_USERNAME: ENC[AES256_GCM,data:hJLu10SefoBzquhd,iv:e5NOm82SmBqAH7JTX4OFug1kKVO+ygaQ8v8JEPikwMA=,tag:zebxC7lDkpnP1TLRMlNjFg==,type:str]
    AUTH_PASSWORD: ENC[AES256_GCM,data:G7T1bLrtKR6+rphu,iv:C6KAfxWYYrkPLipLjP7DJwlLHfbHeCeYrlVTdFrJrlE=,tag:oSdQYPN1ppLL/bNJHJ0faA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19jc9zp5pc7me0wkx28kc2ypr9qh6t9zphn3fdk63ae9dz9a2h5gsh4w866
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZGpEQ0I4K0xSSUtoak0v
            cCsxU1FueTdKVmJkYzhZRjRreVVTVWE1OXlJClViSWVsa3Jab2dwZ3owR1dzdHlB
            ZUJjRGM0cHgxTlQzdzRJdXNVU2Z1WXcKLS0tIG5oM2QyZmlTRisyenJOS3ZyaWxs
            SlBTRHNpTmxtdUk4dE9hSDlwSDVmSGsKJRGp0MSuKFuwbNFFFK8Ut1Wm9S5WSb6r
            e8XOfPNgUi6Ruo+uDpukywoyGlYxw7JHO976HRWKXNacHXKsE3DWuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-03T14:44:46Z"
    mac: ENC[AES256_GCM,data:tl+22IdsurBH6qJn1VK7v1LM9qTBI3/m/LLxlsCheYVcG7pSrGIi3R1I1ZSyGKYrsJvOnyi8ng0ALOozjdfe195C46lSWKuynTcJQHN4i1rQ/RvVGAG9MsiQrTs0HuFmfc1oNlY6NC2Y8h8MMSh0dQNDFxnDGsWM/979+RBpTuY=,iv:myZZ4NeSjzqY7Ci8B449yCweo7YxLEq8gpT/XfGCpa0=,tag:KZbiDpGN14RYJNMhSfVrlw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
