apiVersion: v1
kind: Secret
metadata:
    name: bazarr-apikey
    namespace: default
type: Opaque
data:
    API_KEY: ENC[AES256_GCM,data:U4uGifhyKqq2x43nTFmmftABlCJ0Csd8X0bqUh5PuYjMQnbHdPZe79KORV8=,iv:oEZr6G2c7Cu67qF6fsaVRJ1jGcFT7mhdFJ4dGwF12uY=,tag:+igF5acDmjApt2zwD6teiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19jc9zp5pc7me0wkx28kc2ypr9qh6t9zphn3fdk63ae9dz9a2h5gsh4w866
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZGpEQ0I4K0xSSUtoak0v
            cCsxU1FueTdKVmJkYzhZRjRreVVTVWE1OXlJClViSWVsa3Jab2dwZ3owR1dzdHlB
            ZUJjRGM0cHgxTlQzdzRJdXNVU2Z1WXcKLS0tIG5oM2QyZmlTRisyenJOS3ZyaWxs
            SlBTRHNpTmxtdUk4dE9hSDlwSDVmSGsKJRGp0MSuKFuwbNFFFK8Ut1Wm9S5WSb6r
            e8XOfPNgUi6Ruo+uDpukywoyGlYxw7JHO976HRWKXNacHXKsE3DWuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-03T14:29:05Z"
    mac: ENC[AES256_GCM,data:LgIHBFSvAO4xiWx5K55u7G9Crj+tPmPCVtTCHzCH2zqmR+Sqcrxg9wISJQVdbnOj5tUlvzDnLAvsaECpWSni7en+SQ6CViIEhv6v9DBpcdPkwoXotywtF1WkX58tXg4UfsZ0+GVcInMGNjc7KvBwl0mvmnL0+jEgn2gm+a/BObs=,iv:TAWoXgmowKBPVNoYB58V6lu/NabRul9a9MydfVkMn7o=,tag:II8o3YjYbyFDCRt5JuWF2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
