---
socketLB:
  hostNamespaceOnly: true
autoDirectNodeRoutes: true
bpf:
  masquerade: false # Required for Talos `.machine.features.hostDNS.forwardKubeDNSToHost`
  tproxy: true
cgroup:
  automount:
    enabled: false
  hostRoot: /sys/fs/cgroup
cluster:
  id: 1
  name: "home-kubernetes"
cni:
  exclusive: false
# NOTE: devices might need to be set if you have more than one active NIC on your hosts
# devices: eno+ eth+
endpointRoutes:
  enabled: true
policyAuditMode: true
#policyEnforcementMode: "never"
envoyConfig:
  enabled: true
envoy:
  enabled: true
  debug:
    admin:
      enabled: false
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
l7Proxy: true
ingressController:
  enabled: true
  default: false
  defaultSecretNamespace: network
  defaultSecretName: stiforr-com-production-tls
  loadbalancerMode: shared
  service:
    annotations:
      io.cilium/lb-ipam-ips: 192.168.1.205
clustermesh:
  useAPIServer: false
ipam:
  mode: kubernetes
ipv4NativeRoutingCIDR: "10.69.0.0/16"
k8sServiceHost: 127.0.0.1
k8sServicePort: 7445
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
l2announcements:
  enabled: true
loadBalancer:
  algorithm: maglev
  mode: snat
localRedirectPolicy: true
operator:
  replicas: 1
  rollOutPods: true
rollOutCiliumPods: true
routingMode: native
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
