apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: proxmox-dashboard
    namespace: default
    options:
      annotations:
        grafana-dashboard-folder: Infra
      labels:
        grafana_dashboard: "1"
    files:
      - ./dashboards/proxmox-cluster-flux.json
