apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tubearchivist-redis
  namespace: default
spec:
  hosts:
    - "*"
  tcp:
    - route:
        - destination:
            host: tubearchivist-redis
            port:
              number: 6379
    - match:
        - port: 6379
---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: tubearchivist-redis
  namespace: default
spec:
  selector:
    istio: ingress
  servers:
    - hosts:
        - "*"
      port:
        name: http
        number: 6379
        protocol: tcp
