---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali
  namespace: istio-system
spec:
  chart:
    spec:
      chart: kiali-operator
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
  install:
    crds: Create
  interval: 6h0m0s
  releaseName: kiali-operator
  targetNamespace: istio-system
  upgrade:
    crds: CreateReplace
  values:
    accessibleNamespacesLabel: ""
    affinity: {}
    allowAdHocKialiImage: false
    allowAdHocKialiNamespace: true
    allowAdHocOSSMConsoleImage: false
    allowAllAccessibleNamespaces: true
    allowSecurityContextOverride: false
    clusterRoleCreator: true
    cr:
      annotations: {}
      create: true
      name: kiali
      namespace: istio-system
      spec:
        auth:
          strategy: anonymous
        deployment:
          accessible_namespaces:
          - '**'
        external_services:
          custom_dashboards:
            enabled: true
          grafana:
            dashboards:
            - name: Istio Service Dashboard
              variables:
                namespace: var-namespace
                service: var-service
            - name: Istio Workload Dashboard
              variables:
                namespace: var-namespace
                workload: var-workload
            - name: Istio Mesh Dashboard
            - name: Istio Control Plane Dashboard
            - name: Istio Performance Dashboard
            - name: Istio Wasm Extension Dashboard
            enabled: true
            health_check_url: ""
            in_cluster_url: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local
            is_core: false
            url: https://grafana.internal.stiforr.com
          prometheus:
            url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          istio:
            ingress_gateway_namespace: "istio-ingress"
        istio_labels:
          app_label_name: "app.kubernetes.io/name"
          ingress_gateway_label: "istio=ingress"
          version_label_name: "app.kubernetes.io/version"
    debug:
      enableProfiler: false
      enabled: true
      verbosity: "1"
    env: []
    fullnameOverride: kiali-operator
    image:
      digest: ""
      pullPolicy: Always
      pullSecrets: []
      repo: quay.io/kiali/kiali-operator
      tag: v1.89.3
    metrics:
      enabled: true
    nameOverride: ""
    nodeSelector: {}
    onlyViewOnlyMode: false
    podAnnotations: {}
    podLabels: {}
    priorityClassName: ""
    replicaCount: 1
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
    secretReader:
    - cacerts
    - istio-ca-secret
    securityContext: {}
    tolerations: []
    watchNamespace: istio-system
    watchesFile: ""
