---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ztunnel
  namespace: istio-system
spec:
  chart:
    spec:
      chart: ztunnel
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  dependsOn:
  - name: istiod
    namespace: istio-system
  - name: istio-cni
    namespace: istio-system
  interval: 6h0m0s
  releaseName: ztunnel
  targetNamespace: istio-system
