---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  chartRef:
    kind: OCIRepository
    name: forgejo
    namespace: flux-system
  install:
    createNamespace: true
  interval: 24h0m0s
  releaseName: forgejo
  targetNamespace: forgejo
  values:
    checkDeprecation: true
    clusterDomain: cluster.local
    gitea:
      additionalConfigSources:
        - secret:
            secretName: forgejo-app-ini
      admin:
        passwordMode: keepUpdated
      config:
        APP_NAME: 'Forgejo: Beyond coding. We forge.'
        RUN_MODE: prod
        actions: { }
        admin: { }
        api: { }
        attachment: { }
        avatar: { }
        cache: { }
        camo: { }
        cors: { }
        cron: { }
        database:
          DB_TYPE: postgres
        email.incoming: { }
        federation: { }
        git: { }
        highlight.mapping: { }
        i18n: { }
        indexer:
          ISSUE_INDEXER_TYPE: bleve
          REPO_INDEXER_ENABLED: true
        lfs: { }
        log: { }
        mailer: { }
        markdown: { }
        markup: { }
        metrics: { }
        migrations: { }
        mirror: { }
        oauth2: { }
        oauth2_client: { }
        openid: { }
        other: { }
        packages: { }
        picture: { }
        project: { }
        proxy: { }
        queue: { }
        repo-avatar: { }
        repository: { }
        security: { }
        server:
          SSH_LISTEN_PORT: 2222
          SSH_PORT: 22
        service: { }
        session: { }
        ssh.minimum_key_sizes: { }
        storage: { }
        time: { }
        ui: { }
        webhook: { }
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: monitoring
      oauth: [ ]
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      className: internal
      enabled: true
      hosts:
        - host: git.internal.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - git.internal.${SECRET_DOMAIN}
          secretName: forgejo-tls
    persistence:
      accessModes:
        - ReadWriteOnce
      annotations:
        helm.sh/resource-policy: keep
      claimName: gitea-shared-storage
      create: true
      enabled: true
      mount: true
      size: 10Gi
      storageClass: nfs-client-ssd
    postgresql-ha:
      enabled: false
    postgresql:
      enabled: true
      global:
        postgresql:
          auth:
            database: gitea
            password: gitea
            username: gitea
          service:
            ports:
              postgresql: 5432
      primary:
        persistence:
          size: 10Gi
          storageClass: nfs-client-ssd
    redis:
      architecture: standalone
      enabled: true
      global:
        redis:
          password: changeme
      master:
        count: 1
    redis-cluster:
      cluster:
        nodes: 3
        replicas: 0
      enabled: false
      usePassword: false
    replicaCount: 1
    service:
      http:
        annotations: {}
        clusterIP: None
        externalIPs: null
        externalTrafficPolicy: null
        ipFamilies: null
        ipFamilyPolicy: null
        labels: { }
        loadBalancerClass: null
        loadBalancerIP: null
        loadBalancerSourceRanges: [ ]
        nodePort: null
        port: 3000
        type: ClusterIP
      ssh:
        annotations:
          lbipam.cilium.io/sharing-cross-namespace: "forgejo,network"
          lbipam.cilium.io/sharing-key: "ingress"
          lbipam.cilium.io/ips: "192.168.2.202"
        clusterIP: None
        externalIPs: null
        externalTrafficPolicy: null
        hostPort: null
        ipFamilies: null
        ipFamilyPolicy: null
        labels: { }
        loadBalancerClass: null
        loadBalancerIP: null
        loadBalancerSourceRanges: [ ]
        nodePort: null
        port: 22
        type: LoadBalancer
    signing:
      enabled: false
      existingSecret: ""
      gpgHome: /data/git/.gnupg
      privateKey: ""
