apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
    namespace: forgejo
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:j58555O2cx2j4fF2NmETKkgOP/2ALQ==,iv:tLb1sX4JSoMjbdfiDJ+cA7Mz7jkIZ3Qz7GDZeUxE31g=,tag:j+mFEaSHKe8KZPF04bRvrw==,type:str]
    username: ENC[AES256_GCM,data:nAi9NEO47g==,iv:AziUrUUAe00vXYVAycF1wQDDF+ARkMEykcFde2V3y/c=,tag:lGf1luwpai4vtq0j14lDug==,type:str]
    password: ENC[AES256_GCM,data:+kGruFouXc5SEb7VweQ=,iv:owwRN/qSp5D/1H4L7IeYPB6IXv7RDpagsY91PuUYN90=,tag:JN0W7HxC030JiUknM+pZjw==,type:str]
