apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
    namespace: forgejo
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:j58555O2cx2j4fF2NmETKkgOP/2ALQ==,iv:tLb1sX4JSoMjbdfiDJ+cA7Mz7jkIZ3Qz7GDZeUxE31g=,tag:j+mFEaSHKe8KZPF04bRvrw==,type:str]
    username: ENC[AES256_GCM,data:nAi9NEO47g==,iv:AziUrUUAe00vXYVAycF1wQDDF+ARkMEykcFde2V3y/c=,tag:lGf1luwpai4vtq0j14lDug==,type:str]
    password: ENC[AES256_GCM,data:+kGruFouXc5SEb7VweQ=,iv:owwRN/qSp5D/1H4L7IeYPB6IXv7RDpagsY91PuUYN90=,tag:JN0W7HxC030JiUknM+pZjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19jc9zp5pc7me0wkx28kc2ypr9qh6t9zphn3fdk63ae9dz9a2h5gsh4w866
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSzJWTExIYjRpUHdZRGwv
            Y3ZIcmNvdjk5YTFUbHhZRFR0aWNnaExXN3hvCjZZTWZuS3lTT0Z4bytHUGs4cXoy
            RXlTS20wV3FVNWcwSDM5SHVtM3IwSUEKLS0tIEN3UXNMWmJlOTJMcTBzZE45SEU1
            Yzc1M2UySTVrU2Z6WWJvM0M4Sis3b3cKOYpNqRdMeI/KKgjwoqVsblyzrEjh3ZWk
            oJ477I7VoiieI2RTo3Y5wfr3u3kN7s6lyqnqROyRAs3K6dinMxG1hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-12T02:16:51Z"
    mac: ENC[AES256_GCM,data:Zy8rxRm06gMptC39nw5nhbINOSTXow+cta+dUFhA73Lf3DA9m5TPWFfK5AIYMd3AMeHF23kmgm/x5WQyY6eA7Kdcg/6Hr3WPm0jxV5OOvqX2Oj2kOFPjZtws1rDKe93iG2t1OUbzdLmTwkqrfFLrf9B0XK2EvN8OQDt/sKwHq9o=,iv:d1wMU6vsJ/XG6zIIWP84kgjFsyx8wnY5RDJKGTi5hgs=,tag:8epvq+vWpI+U5dEFeHUyzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
