apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:V+QGdEVfKj0XgpCH0CdtzVUUjWe6Mnebbx4mlWbEn8eL7Nw35dJhjg==,iv:RTK+A/LGGkc+PvgRgUtWGsf8Sq010unG8zCROv7vDFc=,tag:sfKe4Gkp063lILSfEmRYSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19jc9zp5pc7me0wkx28kc2ypr9qh6t9zphn3fdk63ae9dz9a2h5gsh4w866
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTG5QTTNsdENRVzF3WmFB
            eCtHenVDVHoyRzliOHEzTHVnMHE4QWo5Wm40ClFnbHZsL2RlWDZQOUhhNnFFaTZU
            S2MvS3U3dmFKVGVXM2xjbFJtMVhGK0UKLS0tIG5KRHY0dytTTElkbk1tVjlGaklz
            d1d3SFVUa0piYjhrWm1vWFQ1WUpxQzQKK07TPXClBPGkl37mLtHGm1yE6ZepWUZ8
            BkuR3gZ+MeLBGM92FC99iOR6ojBGD9Qi1n77tXeRGppO7+qu4DWlHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-17T15:28:40Z"
    mac: ENC[AES256_GCM,data:vSNPJEAZ9BgBFGu5NSV8dtSm7g7hT1RydxX1LIvz5LUogv1MyzwxRITiDnY0InwArL1KNm23rQSZ9DjdDA4wPWWqKfo0YnHkfFKmDwhY5oxQQvY+YaDqx0AxKMhzOtXMzwUUDLvwBs7AEx6xR8/+LHwn/MFhDBmwXqKppVNemh8=,iv:OddL9j8aj/dbxbi+f+6PzelrFgylWBSet5iFecVyPv8=,tag:YNe3OyFjFcKIzknDrdMA6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
