---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr-new
  namespace: default
spec:
  chartRef:
    kind: OCIRepository
    name: radarr
    namespace: flux-system
  interval: 6h0m0s
  releaseName: radarr-new
  targetNamespace: default
  values:
    exportarrImage:
      pullPolicy: IfNotPresent
      repository: ghcr.io/onedr0p/exportarr
      tag: v2.0.1@sha256:727e7bc8f2f0934a2117978c59f4476b954018b849a010ea6cfb380bd6539644
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/onedr0p/radarr
      tag: 5.11.0.9244@sha256:979669f2573983250746b5220299f05ac57421cf35cb6f71450dd01eb630d03d
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/service-upstream: "true"
        hosts:
          - host: &host radarr-new.internal.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
          - host: radarr.internal.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: radarr-new-tls
            hosts:
              - *host
          - secretName: radarr-tls
            hosts:
              - radarr.internal.${SECRET_DOMAIN}
        integrations:
          traefik:
            enabled: false
    metrics:
      main:
        enabled: true
        endpoints:
          - path: /metrics
            port: metrics
        prometheusRule:
          enabled: false
        targetSelector: metrics
        type: servicemonitor
    persistence:
      config:
        enabled: true
        targetSelector:
          main:
            exportarr:
              mountPath: /config
              readOnly: true
            main:
              mountPath: /config
      nfs:
        enabled: true
        existingClaim: media-pvc-ssd
        targetSelector:
          main:
            main:
              mountPath: /data
    portal:
      open:
        enabled: true
    securityContext:
      container:
        readOnlyRootFilesystem: false
    service:
      main:
        ports:
          main:
            port: 7878
      metrics:
        enabled: '{{ .Values.metrics.main.enabled }}'
        ports:
          metrics:
            enabled: true
            port: 7879
        type: ClusterIP
    updated: true
    workload:
      main:
        podSpec:
          containers:
            exportarr:
              args:
                - radarr
              enabled: '{{ .Values.metrics.main.enabled }}'
              env:
                CONFIG: /config/config.xml
                INTERFACE: 0.0.0.0
                PORT: '{{ .Values.service.metrics.ports.metrics.port }}'
                URL: '{{ printf "http://%v:%v" (include "tc.v1.common.lib.chart.names.fullname" $) .Values.service.main.ports.main.port }}'
              envFrom:
                - secretRef:
                    name: radarr-apikey
                    expandObjectName: false
              imageSelector: exportarrImage
              probes:
                liveness:
                  enabled: true
                  path: /healthz
                  port: '{{ .Values.service.metrics.ports.metrics.port }}'
                  type: http
                readiness:
                  enabled: true
                  path: /healthz
                  port: '{{ .Values.service.metrics.ports.metrics.port }}'
                  type: http
                startup:
                  enabled: true
                  path: /healthz
                  port: '{{ .Values.service.metrics.ports.metrics.port }}'
                  type: http
            main:
              env:
                RADARR__PORT: '{{ .Values.service.main.ports.main.port }}'
              probes:
                liveness:
                  enabled: true
                  path: /ping
                  type: http
                readiness:
                  enabled: true
                  path: /ping
                  type: http
                startup:
                  enabled: true
                  path: /ping
                  type: http
