---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki-stack
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 1h0m0s
  releaseName: loki
  targetNamespace: monitoring
  values:
    promtail:
      enabled: true
      sidecar:
        configReloader:
          enabled: true
          serviceMonitor:
            enabled: false
    loki:
      enabled: true
      image:
        repository: grafana/loki
        tag: 3.2.0
        pullPolicy: IfNotPresent
      isDefault: false
      serviceMonitor:
        enabled: true
        additionalLabels:
          app.kubernetes.io/part-of: kube-prometheus-stack
      persistence:
        enabled: false
        accessModes:
          - ReadWriteOnce
        size: 10Gi
        storageClassName: openebs-hostpath
      config:
        table_manager:
          retention_deletes_enabled: true
          retention_period: 12h
