apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: loki
  namespace: monitoring
spec:
  hosts:
    - loki-gateway.monitoring.svc.cluster.local
  http:
    - match:
        - port: 80
      route:
        - destination:
            host: loki-gateway.monitoring.svc.cluster.local
            port:
              number: 80
