---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr-anime
  namespace: default
spec:
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.4.0
  interval: 12h0m0s
  releaseName: radarr-anime
  targetNamespace: default
  values:
    controllers:
      main:
        containers:
          exportarr:
            enabled: true
            args:
              - radarr
            env:
              - name: URL
                value: http://radarr-anime:8888
              - name: PORT
                value: 7879
              - name: ENABLE_ADDITIONAL_METRICS
                value: true
              - name: DISABLE_SSL_VERIFY
                value: true
              - name: APIKEY
                valueFrom:
                  secretKeyRef:
                    name: radarr-anime-apikey
                    key: APIKEY
            image:
              repository: ghcr.io/onedr0p/exportarr
              tag: v2.0.1
          radarr:
            env:
              - name: TZ
                value: America/Chicago
              - name: PUID
                value: 1000
              - name: PGID
                value: 1000
            image:
              repository: linuxserver/radarr
              tag: 5.11.0
            resources:
              limits:
                cpu: 500m
                memory: 1Gi
              requests:
                cpu: 100m
                memory: 500m
        enabled: true
        type: deployment
    global:
      fullnameOverride: radarr-anime
      labels:
        app: radarr-anime
    ingress:
      radarr-anime:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/enable-opentelemetry: "true"
          nginx.ingress.kubernetes.io/otel-service-name: radarr-anime
          nginx.ingress.kubernetes.io/service-upstream: "false"
        className: cilium
        enabled: true
        hosts:
          - host: radarr-anime.internal.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: radarr-anime
        tls:
          - hosts:
              - radarr-anime.internal.${SECRET_DOMAIN}
            secretName: radarr-anime-tls
    persistence:
      config:
        accessMode: ReadWriteOnce
        enabled: true
        size: 1Gi
        storageClass: nfs-client-ssd
        type: persistentVolumeClaim
      data:
        enabled: true
        existingClaim: media-pvc-ssd
      custom-services:
        enabled: true
        type: persistentVolumeClaim
        storageClass: nfs-client-ssd
        accessMode: ReadWriteOnce
        size: 1Gi
        advancedMounts:
          main:
            radarr:
              - path: /custom-services.d
                readOnly: false
      custom-cont-init:
        enabled: true
        type: configMap
        name: script-init
        advancedMounts:
          main:
            radarr:
              - path: /custom-cont-init.d
                readOnly: false
    service:
      exportarr:
        controller: main
        enabled: true
        ports:
          metrics:
            appProtocol: http
            enabled: true
            port: 7879
            primary: false
            protocol: HTTP
        primary: false
      radarr-anime:
        controller: main
        enabled: true
        ports:
          http:
            appProtocol: http
            enabled: true
            port: 8888
            targetPort: 7878
            protocol: HTTP
    serviceAccount:
      create: true
    serviceMonitor:
      exportarr:
        enabled: true
        endpoints:
          - interval: 4m
            path: /metrics
            port: metrics
            scheme: http
            scrapeTimeout: 90s
        serviceName: radarr-anime-exportarr
