---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tautulli
  namespace: default
spec:
  chart:
    spec:
      chart: tautulli
      sourceRef:
        kind: HelmRepository
        name: tautulli
        namespace: flux-system
  interval: 6h0m0s
  releaseName: tautulli
  targetNamespace: default
  values:
    global:
      fallbackDefaults:
        storageClass: openebs-hostpath
        pvcSize: 10Gi
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/tautulli/tautulli
      tag: v2.14.5@sha256:6017b491d8e9100a97391b639fff5824ad36a315c69aae3c9ed78407994a626e
    TZ: America/Chicago
    persistence:
      config:
        enabled: true
        mountPath: /config
    portal:
      open:
        enabled: true
    service:
      main:
        ports:
          main:
            port: 8181
            targetPort: 8181
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: false
        primary: true
        required: true
        labels: { }
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/service-upstream: "false"
        ingressClassName: "internal"
        hosts:
          - host: &host tautulli.internal.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: tautulli-tls
            certificateIssuer: ""
            hosts:
              - *host
    workload:
      main:
        podSpec:
          containers:
            main:
              args:
                - --config
                - /config/config.ini
                - --datadir
                - /config
              command:
                - python
                - Tautulli.py
