apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-all-ingress
  namespace: default
spec:
  enableDefaultDeny:
    egress: false
    ingress: false
  endpointSelector: {}
  ingress:
    - {}
  egress:
    - {}
  # L7 visibility for HTTP traffic
  l7:
    - ports:
        - port: "80"
          protocol: TCP
      rules:
        http:
          - {}
