apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: "all-ports-policy"
  namespace: default
spec:
  endpointSelector: {}
  ingress:
    - toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
            - port: "8080"
              protocol: TCP
            - port: "8443"
              protocol: TCP
            - port: "3000"
              protocol: TCP
            - port: "5000"
              protocol: TCP
            - port: "5432"
              protocol: TCP
            - port: "6379"
              protocol: TCP
            - port: "27017"
              protocol: TCP
            - port: "5055"
              protocol: TCP
            - port: "9962"
              protocol: TCP
            - port: "9880"
              protocol: TCP
            - port: "10256"
              protocol: TCP
            - port: "7445"
              protocol: TCP
            - port: "20001"
              protocol: TCP
            - port: "8084"
              protocol: TCP
  egress:
    - toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
            - port: "8080"
              protocol: TCP
            - port: "8443"
              protocol: TCP
            - port: "3000"
              protocol: TCP
            - port: "5000"
              protocol: TCP
            - port: "5432"
              protocol: TCP
            - port: "6379"
              protocol: TCP
            - port: "27017"
              protocol: TCP
            - port: "5055"
              protocol: TCP
            - port: "9962"
              protocol: TCP
            - port: "9880"
              protocol: TCP
            - port: "10256"
              protocol: TCP
            - port: "7445"
              protocol: TCP
            - port: "20001"
              protocol: TCP
            - port: "8084"
              protocol: TCP
            - port: "32400"
              protocol: TCP
            - port: "9121"
              protocol: ANY
            - port: "9187"
              protocol: ANY
            - port: "9697"
              protocol: TCP
