apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: "allow-all-ports-policy"
  namespace: default
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - {}
      toPorts:
        - ports:
            - port: "0"
              protocol: TCP
            - port: "0"
              protocol: UDP
  egress:
    - toEndpoints:
        - {}
      toPorts:
        - ports:
            - port: "0"
              protocol: TCP
            - port: "0"
              protocol: UDP
    - toEntities:
        - "all"
