---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./pvc-ssd.yaml
  - ./sonarr
  - ./overseerr
  #  - ./jackett
  - ./nfs-subdir-external-ssd
  - ./tubearchivist
  #  - ./plex
  - ./tautulli
  - ./radarr
  - ./prowlarr
  - ./filebrowser
  #  - ./authentik
  - ./proxmox
  - ./influx
#  - ./bazarr
  # - ./network-policy.yaml
  - ./doplarr
  #  - ./autobrr
  #  - ./nzbget
  #  - ./otel-collector.yaml
  #  - ./homepage
  - ./qbittorrent
  - ./adguard
  # - ./radarr-anime
  # - ./sonarr-anime
  #  - ./mastodon
#  - ./rocketchat
#  - ./uptime-kuma
  - ./flux-alerts.yaml
  - ./discord-webhook.sops.yaml
#  - ./mailu/ks.yaml
  - ./lutho
  - ./checkmk
  - ./glances
configMapGenerator:
  - name: general-dashboards
    namespace: default
    options:
      annotations:
        grafana-dashboard-folder: Media
      labels:
        grafana_dashboard: "1"
    files:
      - ./general-dashboards/media-dashboard.json
