---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./pvc-ssd.yaml
  - ./sonarr
  - ./overseerr
  - ./nfs-subdir-external-ssd
  - ./tubearchivist
  - ./tautulli
  - ./radarr
  - ./prowlarr
  - ./filebrowser
  - ./proxmox
  - ./influx
  - ./doplarr
  - ./homepage
  - ./flux-alerts.yaml
  - ./discord-webhook.sops.yaml
  - ./glances
  - ./budibase
configMapGenerator:
  - name: general-dashboards
    namespace: default
    options:
      annotations:
        grafana-dashboard-folder: Media
      labels:
        grafana_dashboard: "1"
    files:
      - ./general-dashboards/media-dashboard.json
