---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./pvc-ssd.yaml
  - ./sonarr
  - ./overseerr
  - ./jackett
  - ./nfs-subdir-external-ssd
  - ./tubearchivist
  - ./plex
  - ./tautulli
#  - ./radarr-new
  - ./prowlarr
  - ./filebrowser
  - ./authentik
  - ./proxmox
  - ./influx
  - ./bazarr

configMapGenerator:
  - name: general-dashboards
    namespace: default
    options:
      labels:
        grafana_dashboard: "1"
    files:
      - ./general-dashboards/media-dashboard.json
