apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "l7-visibility-all"
  namespace: default
spec:
  endpointSelector: {}
  ingress:
    - toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
            - port: "8080"
              protocol: TCP
            - port: "8443"
              protocol: TCP
            - port: "3000"
              protocol: TCP
            - port: "5000"
              protocol: TCP
            - port: "5432"
              protocol: TCP
            - port: "6379"
              protocol: TCP
            - port: "27017"
              protocol: TCP
            - port: "5055"
              protocol: TCP
          rules:
            http: [{}]
  egress:
    - toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
            - port: "8080"
              protocol: TCP
            - port: "8443"
              protocol: TCP
            - port: "3000"
              protocol: TCP
            - port: "5000"
              protocol: TCP
            - port: "5432"
              protocol: TCP
            - port: "6379"
              protocol: TCP
            - port: "27017"
              protocol: TCP
          rules:
            http: [{}]
