apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-all-within-namespace
  namespace: default
spec:
  description: Allow all within namespace
  egress:
    - toEndpoints:
        - { }
  endpointSelector: { }
  ingress:
    - fromEndpoints:
        - { }
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: dns-visibility
  namespace: default
spec:
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: '*'
    - toFQDNs:
        - matchPattern: '*'
    - toEntities:
        - all
  endpointSelector:
    matchLabels: { }
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: l7-egress-visibility
  namespace: default
spec:
  description: L7 policy
  egress:
    - toEntities:
        - world
  endpointSelector: { }
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: nginx-ingress-l7-policy
  namespace: default # Adjust the namespace if needed
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/instance: ingress-nginx-internal
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: ingress-nginx
            app.kubernetes.io/instance: ingress-nginx-internal
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
          rules:
            http:
              - method: GET
                path: "/.*" # This example matches all paths; adjust as needed
              - method: POST
                path: "/.*" # You can be more specific with paths and methods
    - toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "80"
              protocol: TCP
          rules:
            http:
              - path: "/.*" # L7 visibility for all HTTP requests
                method: GET
              - path: "/.*"
                method: POST
  egress:
    - toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "80"
              protocol: TCP
