apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-all-within-namespace
  namespace: default
spec:
  description: Allow all within namespace
  egress:
    - toEndpoints:
        - { }
  endpointSelector: { }
  ingress:
    - fromEndpoints:
        - { }
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: dns-visibility
  namespace: default
spec:
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: '*'
    - toFQDNs:
        - matchPattern: '*'
    - toEntities:
        - all
  endpointSelector:
    matchLabels: {}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: l7-egress-visibility
  namespace: default
spec:
  description: L7 policy
  egress:
    - toEntities:
        - world
  endpointSelector: {}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: l7-ingress-visibility
  namespace: default
spec:
  description: L7 policy
  endpointSelector: {}
  ingress:
    - toPorts:
        - ports:
            - port: "6379"
              protocol: TCP
            - port: "8000"
              protocol: TCP
            - port: "9200"
              protocol: TCP
            - port: "50000"
              protocol: TCP
            - port: "5055"
              protocol: TCP
            - port: "15090"
              protocol: TCP
            - port: "443"
              protocol: TCP
            - port: "80"
              protocol: TCP
            - port: "7878"
              protocol: TCP
            - port: "8989"
              protocol: TCP
          rules:
            http:
              - {}
