apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: radarr
  namespace: default
spec:
  mtls:
    mode: UNSET
  portLevelMtls:
    7878:
      mode: DISABLE
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: sonarr
  namespace: default
spec:
  mtls:
    mode: UNSET
  portLevelMtls:
    8989:
      mode: DISABLE
