apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: default
  namespace: default
spec:
  selector:
    matchLabels:
      "k8s:app.kubernetes.io/name": radar
      "k8s:app.kubernetes.io/name": sonarr
      "k8s:app.kubernetes.io/name": overseerr
  mtls:
    mode: UNSET
  portLevelMtls:
    7878:
      mode: DISABLE
    8989:
      mode: DISABLE
