apiVersion: v1
kind: Secret
metadata:
    name: radarr-config
type: Opaque
stringData:
    config.xml: ENC[AES256_GCM,data:4FdPgNdq0eqKBOmUAxqmwBNWXjFTQm2RxgqG4i3JmAcVUrLdO1av+rGJ6GZpDawkkX3Jox996JP02+/NKpdPPcrRhAMCHJf8WF87jjRd08Ms84J0ipYbdagSDR0rZp4z2A6fgmdFWVpKZgV9tpE9iJ+ymxGEa6OKzigb/UgkxCTwIFoyr1g1FOCJMJK341VfrxDD5zg8ks/ZZhcyDiDqwXYKF/EyjtC+M1t433/vFzpHCiib9dzczx7rSoZ2/jJjtJ65Eqebx0a0WzeWfOOk0P1DDPWK+2lHq4wM4qZ2llN2ufJJ+M4k/iQuzEH6dpSUaSQUdpSB14Q1bMB3NjTWDy0rF72irz8skHF7axLHc8t4o5YtQnzgbWP9FyA0bBaeMSeOPgW1Gj4QsL5sPXtnJjAAH4XEFyKqSs4hwe6NDSwSMci0BAiOdOE8Osq1LbSpFfn1+LyXL/cqYfoNS4iwcl9OoK9z2eSZ26dlnXmha5TOmfEQ9PT6SzxeoQsG4FFzVa09/5CoDQC4HZwjNG0fCh80k29jXY+vPqVTclbziVN1DjB+oYBaLf7GotrGdS8gaR6vSHnudj9Imn8=,iv:O8PyGGDhfwqi6Xs9bvbA3K5BtKAMRZStnX5K4/ioq5A=,tag:tiIXRh9rJ20nKOsrVhqyEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19jc9zp5pc7me0wkx28kc2ypr9qh6t9zphn3fdk63ae9dz9a2h5gsh4w866
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSkplbFBqbTRyMCtrWXBz
            ellKbVZwRmJpTWJPb1NzMG1RVWg5M1BCeHdFClV0K3FNN2p4MFhXcDh3dVlGVEQw
            aFhwOENRNzExMjlzVWFCR1VtVG9XdncKLS0tIGdlSDRha1lmR1UyY3NVeVlaa1Vz
            dmFQajE2L3VJRFNaWlRoa2pHZTFkRFEKMHHL0jb9+Yt9eSN/SMZ9Tw5YzjlTn387
            jI1xii2MAJgplWLKmvZfvNX9XsvxI3Jxbkqv0UOYc229pI0ug6fWoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-08T20:48:24Z"
    mac: ENC[AES256_GCM,data:yTe95apqIa7z17kGdrjmgpNW5DT7kc0ogRypfkAUhDVQoA5N+0+4TNJzlvSvMGp6JQJKVLUl6ELxyMXALBLBsJBgrIXzUDfu0PGd/jdY2PSPub/09Mc28yN2QwOHE5qCbaixlukwBs/qN/PM2A1GJgoecI0b6K+J5iod2eGeQTY=,iv:eH83iBKEO1BidhbAUmsqC+CaXpFif6yrJluOhqmOMqo=,tag:LNOemUuCmSr48LBGy4sgdg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
