apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
    namespace: default
type: Opaque
stringData:
    AUTH_PASSWORD: ENC[AES256_GCM,data:PaH76dUM,iv:AN/5YHzDZBCFXzWAqpnPQ5r31czsFIwWqhzszdKc0a4=,tag:CjARBFumNo4Sa6jOQubvSw==,type:str]
    AUTH_USERNAME: ENC[AES256_GCM,data:4lOHoTHBOw==,iv:v3h3BGoC/QwWtxhO+WHwIjWnOjqsvgTYVja+V6PeeIo=,tag:2gzr5YGrBlCMBp5kL6COpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qd2k83kj5ket4qp63rfa456pt5amx5j58sx0dk204crfsmjqvpks4jucs2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUXNoRDhNamRFQW41SUV0
            NmE3T2U1ZDZWaEdqVHpsTmJuVHpWeVJjL0JNCkQveWZ2SVJCME5WcloxY0lJWnRO
            clBVYnRsbjFGdDlWem9qYk9uRmdIazgKLS0tIEE4bmpaQy80SEpkVGUrREtJTEY5
            TzNDVmxIVUJueS9xNjZVTElUMmJIWUkKYw3ma1L0HmktL17gGeOKWNkTvXvMTiaA
            uPdwHcuMR1qyqhfEDiwW37uGVLh6/oB4A14b1CO+5D5ZxSmO9+9JQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-25T14:07:33Z"
    mac: ENC[AES256_GCM,data:k14PeGM++g0tf5cxIMVO+t0uym3NjjvH29/N8U4qubumTlF2cK0LSEJ1xGyarexnXRgHGzvdhzxOX4YqFO1SfKAf7nFh8BdJ96hglSoPIMq9Q3wuWJWsThJKYZ8I89PSUhV9N5s5fyYeIBU/pgXyppha8rxuSr2hBSZkRVCfj3Y=,iv:hFJfCDgUwF9U2EVFy1FXolFLOoyKI9t40gbQu1E/3Lw=,tag:99AoNt/XmQt87Y3yZXh9BQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
