apiVersion: v1
kind: Secret
metadata:
    name: radarr-apikey
    namespace: default
type: Opaque
stringData:
    APIKEY: ENC[AES256_GCM,data:uo6Oz34lfj0oa7XaGJ0qkPDt6xglCv59QaCfJQfwmAByp5GqYBjkSpeQiw0=,iv:N2EupaliiZpzptmKg+ych8hMGS876Gleqg2PUE7HnfI=,tag:to8y9Lv1mOQrNE661mz6lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19jc9zp5pc7me0wkx28kc2ypr9qh6t9zphn3fdk63ae9dz9a2h5gsh4w866
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcWYxY0kxZ0lMSHRBMSsy
            YkxST1c1aHJ6YXhYYmdVK0ZRb2h1OXB1SUFVCnRETGVXWXRGcjlEa2tXejRaYVM2
            dVRtYWlaamlsa28yK3VQVUpmNnY1TW8KLS0tIGJpVkFnQ0tUci91ajY4V0t3bE5m
            ODFiZ0ZNNldoaFRNQ1pvMkZrczBmbncKwXszjlYxaOQ2VC17LJpEFQOoquoswkM/
            2fkREaeaVQUm4XA/tLzGvzbVlCh1nGa0/GaAvb3zU5qkD730PlbuNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-08T21:11:54Z"
    mac: ENC[AES256_GCM,data:4jaJpvLQdJK8oSrEfVO+RDfn6NqgSZSNbOJfHulh5D6x+n5wArBE2I1DXKDA8r3VVv7433ddMrmvOeowetmnQn+txExIe/2LF3UbTcZ3T+ceuqH1IMi8fQKn74e98v5eOLFi0iwr2n2YjSM0Hqo+HRnZRrLFFP0hDRb4tmpycvc=,iv:kUKj7hlgINfkUgkWFEzvjK7DGovei1EkzWke+pkedUI=,tag:f4R33TkD8PjmLpFDJydCAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
