apiVersion: v1
kind: Secret
metadata:
    name: radarr-apikey
    namespace: default
type: Opaque
stringData:
    APIKEY: ENC[AES256_GCM,data:jM22,iv:Fq/LYfgiJ19f9cvlXVK9fS7hXDe/R/eFWKaVmFA5cPA=,tag:aoIF/GIog0qaPyxq6rvUJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qd2k83kj5ket4qp63rfa456pt5amx5j58sx0dk204crfsmjqvpks4jucs2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUXNoRDhNamRFQW41SUV0
            NmE3T2U1ZDZWaEdqVHpsTmJuVHpWeVJjL0JNCkQveWZ2SVJCME5WcloxY0lJWnRO
            clBVYnRsbjFGdDlWem9qYk9uRmdIazgKLS0tIEE4bmpaQy80SEpkVGUrREtJTEY5
            TzNDVmxIVUJueS9xNjZVTElUMmJIWUkKYw3ma1L0HmktL17gGeOKWNkTvXvMTiaA
            uPdwHcuMR1qyqhfEDiwW37uGVLh6/oB4A14b1CO+5D5ZxSmO9+9JQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-22T03:46:46Z"
    mac: ENC[AES256_GCM,data:eOPkR+NS/SaZLy6RgmrsIuTlbMYPW0wOuzSq7O+Se9YluMHjX1IjZTVIBuw0s8hMiyzjFV66aP/Wt0lr2Pgyb1ZKrz7AF34NsqKEibXA7bZhBCZKfsYw17u5ivZKXkbucjjr06VhAytFUpAQJ3j9KmEpPAueYEpzSKDh+kT9Vr8=,iv:MY8wwYcvZtxOK3xvZ4MO5+2cPkqVlO+ahDJO7G7Sk7Q=,tag:JOHB6RIQT5B9RZ525wPlBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
