---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger-operator
  namespace: istio-system
spec:
  chart:
    spec:
      chart: jaeger-operator
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: jaeger
        namespace: flux-system
  install:
    crds: Create
  interval: 6h0m0s
  releaseName: jaeger-operator
  targetNamespace: istio-system
  upgrade:
    crds: CreateReplace
  values:
    affinity: {}
    certs:
      certificate:
        create: true
        issuerKind: Issuer
        namespace: ""
        secretName: ""
      issuer:
        create: true
        name: ""
    containerSecurityContext: {}
    extraArgs: {}
    extraEnv: []
    extraLabels: {}
    hostNetwork: false
    image:
      imagePullSecrets: []
      pullPolicy: IfNotPresent
      repository: jaegertracing/jaeger-operator
      tag: 1.60.1
    jaeger:
      create: false
      namespace: null
      spec: {}
    metricsPort: 8383
    nodeSelector: {}
    priorityClassName: null
    rbac:
      clusterRole: true
      create: true
      pspEnabled: false
    replicaCount: 1
    resources: {}
    securityContext: {}
    service:
      annotations: {}
      type: ClusterIP
    serviceAccount:
      annotations: {}
      create: true
      name: null
    serviceExtraLabels: {}
    tolerations: []
    topologySpreadConstraints: []
    webhooks:
      mutatingWebhook:
        create: true
      port: 9443
      service:
        annotations: {}
        create: true
        name: ""
      validatingWebhook:
        create: true
