apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:TtiSM3qlog==,iv:ivIeDH8NlKgKXwGPPVGm864K4CSIZxkjRJiSDTbNA9w=,tag:m3kgKLGCIqt8WCEvVRwZpg==,type:str]
    password: ENC[AES256_GCM,data:gXFxeYwAi3FY,iv:xOSn3Vgw2YSVey6hAAOYHuX3TJgHTa6Z7ahnGpim5zI=,tag:ZP7B8g0QbbTA6n+f4fFLpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qd2k83kj5ket4qp63rfa456pt5amx5j58sx0dk204crfsmjqvpks4jucs2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidDBUTG5jK3ZQVGF6V3BZ
            dVVEdFdBQWVYdG5IVlluT3NOemRweENvUWxjCld0a2VVZnFpWEkycDVXdldBY202
            a1A3eVZmcko5a3RZbTRPOGpLRmR3ZUkKLS0tIEdpcENqNmNxUzFKemdYK2YwMVRl
            MUkrQ1BqblBkTnJEbmh1SCtUMVNYejQKeL4j3Pr/uHHxz+iByBOlgGWu4sxdd5EI
            ufDLoz+pZ7J6ypu3rW7Yye6T8ksbGFnEAW0lc/bQaDHbxyiPqBsCFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-29T14:37:33Z"
    mac: ENC[AES256_GCM,data:LxLhmLEq9zx8/xHS4tpWD5BYkTQUDJafPFsVd7RLWInBsaaxI54XrlooOOsRb6KzpHAP5ERkScipl+Q/qfgp+HEZ4qwYYSddquPMIWPcTY6E0qA2DtJbSrFMC2yEoQR8vzLSM9YkFSgwE+v4sTLUTaRo1Vxon67+ZskMPlX1iQk=,iv:h40BCnfySSlq5juBVl/lWOFZfYR4HP7cL/wLY78MuSY=,tag:gpO0NLQrvaAdxYDX5HuVpw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
