apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Rso43zqXh6se5A==,iv:Q2mAiRNwjqWi6isWrLIBthQoqpsUEJ4qMvV4D4Rz1ew=,tag:yTbmfN94fqDpHDfhGBc/dA==,type:str]
    password: ENC[AES256_GCM,data:pdwUHP6GrI3NOmT6kkNoeUsNrYUCTUa7qGJRLmgMhIQHzEHgOAFj4fBird1Xp78F/j1czre3auhB1Gcn,iv:2zmmGDMaXNN1TdBlLEEwoItrCIIi6pVR0/O1UNIiwjY=,tag:rCvmNuowYHiIDBYoyOzKQw==,type:str]
