---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mailu
  namespace: default
spec:
  chart:
    spec:
      chart: mailu
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: mailu
        namespace: flux-system
      version: 2.1.1
  interval: 24h0m0s
  releaseName: mailu
  targetNamespace: default
  valuesFrom:
    - kind: ConfigMap
      name: mailu-config
      optional: false
      valuesKey: mailu-values.yaml
  values:
    existingSecret: mailu-secret
    timezone: America/Chicago
    initialAccount:
      enabled: true
      existingSecret: mailu-secret
      existingSecretPasswordKey: user-password
      mode: "update"
    subnet: 10.69.0.0/16
    postgresql:
      enabled: true
      auth:
        existingSecret: mailu-secret
      primary:
        persistence:
          enabled: false
    persistence:
      single_pvc: true
      size: 10Gi
      storageClass: openebs-hostpath
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      ingressClassName: cilium
    redis:
      master:
        persistence:
          enabled: true
          size: 1Gi
          storageClass: openebs-hostpath
