---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: spegel-helm-values
    files:
      - values.yaml=./helm-values.yaml
  - name: spegel-dashboard
    options:
      labels:
        grafana_dashboard: "1"
    files:
      - ./dashboards/spegel.json
configurations:
  - kustomizeconfig.yaml
