---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubeshark
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: kubeshark
      version: 52.3.82
      sourceRef:
        kind: HelmRepository
        name: kubeshark
        namespace: flux-system
  targetNamespace: monitoring
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullnameOverride: "kubeshark"
    tap:
      persistentStorage: true
      storageClass: nfs-client-ssd
      storageLimit: 5Gi
    ingress:
      enabled: true
      className: nginx
      annotations:
        hajimari.io/icon: mdi:shark-fin
        nginx.ingress.kubernetes.io/service-upstream: "true"
      host: &host "kubeshark.internal.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - *host
          secretName: kubeshark-tls
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 500Mi
