---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubeshark
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: kubeshark
      version: 42.0.0
      sourceRef:
        kind: HelmRepository
        name: kubeshark
        namespace: flux-system
  targetNamespace: monitoring
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: mdi:shark-fin
        hosts:
          - host: &host "kubeshark.internal.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 500Mi
