apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: nodejs-instrumentation
  namespace: default
spec:
  exporter:
    endpoint: http://istio-collector-collector.istio-system.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
    - b3
    - jaeger
  sampler:
    type: parentbased_traceidratio
    argument: "1"
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: python-instrumentation
  namespace: default
spec:
  exporter:
    endpoint: http://istio-collector-collector.istio-system.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
    env:
      - name: OTEL_PYTHON_DISABLED_INSTRUMENTATIONS
        value: opentelemetry-instrumentation-celery,opentelemetry-instrumentation-aws-lambda
#  python:
#    env:
#      - name: OTEL_LOGS_EXPORTER
#        value: otlp_proto_http
#      - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
#        value: 'true'
