apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: nodejs-instrumentation
  namespace: default
spec:
  exporter:
    endpoint: http://istio-collector-collector.istio-system.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
    - b3
    - jaeger
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  nodejs:
    env:
      - name: OTEL_NODE_DISABLED_INSTRUMENTATIONS
        value: fs
      - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
        value: DELTA
      - name: OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION
        value: BASE2_EXPONENTIAL_BUCKET_HISTOGRAM
      - name: OTEL_EXPORTER_OTLP_LOGS_PROTOCOL
        value: grpc
      - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
        value: grpc
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: python-instrumentation
  namespace: default
spec:
  exporter:
    endpoint: http://istio-collector-collector.istio-system.svc.cluster.local:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
    env:
      - name: OTEL_PYTHON_DISABLED_INSTRUMENTATIONS
        value: fs
#  python:
#    env:
#      - name: OTEL_LOGS_EXPORTER
#        value: otlp
#      - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
#        value: 'true'
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: dotnet-instrumentation
  namespace: default
spec:
  exporter:
    endpoint: http://istio-collector-collector.istio-system.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  dotnet:
    env:
      - name: OTEL_EXPORTER_OTLP_LOGS_PROTOCOL
        value: grpc
      - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
        value: grpc
      - name: OTEL_DOTNET_AUTO_TRACES_CONSOLE_EXPORTER_ENABLED
        value: "true"
