apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-node-collector
  namespace: observability
  labels:
    app: otel-node-collector
spec:
  mode: daemonset
  config:
    processors:
      resourcedetection:
        detectors: [env, system]
      cumulativetodelta:
      batch:
        send_batch_size: 10000
        timeout: 10s

    receivers:
      otlp:
        protocols:
          grpc:
          http:
      hostmetrics:
        scrapers:
          cpu:
          disk:
          filesystem:
          load:
          memory:
          network:
          paging:

    exporters:
      debug:
      otlp/uptrace:
        endpoint: http://my-uptrace:14317
        tls: { insecure: true }
        headers:
          uptrace-dsn: 'http://project2_secret_token@my-uptrace:14318?grpc=14317'

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/uptrace, debug]
        metrics:
          receivers: [otlp]
          processors: [cumulativetodelta, batch]
          exporters: [otlp/uptrace, debug]
        metrics/host:
          receivers: [hostmetrics]
          processors: [cumulativetodelta, batch, resourcedetection]
          exporters: [otlp/uptrace, debug]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/uptrace, debug]
