apiVersion: v1
kind: Secret
metadata:
    name: komodor-secret
    namespace: komodor
stringData:
    apiKey: ENC[AES256_GCM,data:Bi48NrTw1voZPX70hnSzHJVPCFyvvYon3O0oSegFE34ikxt8AsTrJlh0VCklaCPa,iv:BlSeTZWkmn8SSzxn/2INpnrkp7HTVaL+CQtr0gCI1BQ=,tag:MhKol3+76Zb0hzxjbSgWLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19jc9zp5pc7me0wkx28kc2ypr9qh6t9zphn3fdk63ae9dz9a2h5gsh4w866
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGR01IU1ZQWkNFWHpTTVE0
            TzdvSGN0TGZ6UzdmWUk2Y25pY2ZOSFh1Snc4Ck5EWk5TTzRtUlVUWHNTL2R4YjVu
            citETHhNTjYzR2pLSWZPK3lUa0RuYlEKLS0tIHdVYWV4R1FiaGhWUlZ3bHI5c0Ux
            cDlYUk1OQ2ZKQlEyejhMaWRXSGtIYlEKFhj8GSt59xRautPVoMt9L4DKVA1EwOLh
            opHpToyQH65eyCXIWethKrRGarxJIRCqEzaQyg/RuLpr9AlA66VVRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-06T07:08:13Z"
    mac: ENC[AES256_GCM,data:G/m1ZpBebo5bEs0n9OD/dGz2IxADQg9FClcr3ks9odIREgbpWJA5VDJ9yv2zVCBNjT0kWRih7A12dMzDtNfDmaYTT1J0ejcBTfHZagKwPf0R2lclvk1ynF6GXTfegf9/XNgdHsRMfVdYBDeB3wK9na84bIpvS+Ae7o7S+ICaKik=,iv:UdmdcBLRtMTjEyr1U/tqwsSileTOEMy19rGjmLn0aGo=,tag:vk2VlLF8wtm536s91xdjqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
