---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-crds
  namespace: linkerd
spec:
  chart:
    spec:
      chart: linkerd-crds
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
  install:
    crds: Create
  interval: 6h0m0s
  targetNamespace: linkerd
  upgrade:
    crds: CreateReplace
