---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-jaeger
  namespace: linkerd-jaeger
spec:
  chart:
    spec:
      chart: linkerd-jaeger
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
  install:
    createNamespace: true
  interval: 6h0m0s
  targetNamespace: linkerd-jaeger
  values:
    clusterDomain: cluster.local
    collector:
      GID: null
      UID: null
      command: /otelcol-contrib
      config:
        exporters:
          otlp:
            endpoint: http://jaeger-collector.observability.svc.cluster.local:4317
            tls:
              insecure: true
        extensions:
          health_check: null
        processors:
          batch: null
        receivers:
          otlp:
            protocols:
              grpc:
              http:
          opencensus:
          zipkin:
          jaeger:
            protocols:
              grpc:
              thrift_http:
              thrift_compact:
              thrift_binary:
        service:
          extensions: [health_check]
          pipelines:
            traces:
              receivers: [otlp,opencensus,zipkin,jaeger]
              processors: [batch]
              exporters: [otlp]
      enabled: true
      env: []
      image:
        name: otel/opentelemetry-collector-contrib
        pullPolicy: ""
        version: 0.108.0
      nodeSelector:
        kubernetes.io/os: linux
      replicas: 1
      resources:
        cpu:
          limit: null
          request: null
        ephemeral-storage:
          limit: ""
          request: ""
        memory:
          limit: null
          request: null
      tolerations: null
    commonLabels: {}
    createNamespaceMetadataJob: true
    defaultGID: 2103
    defaultUID: 2103
    enablePSP: false
    enablePodAntiAffinity: false
    imagePullSecrets: []
    jaeger:
      GID: null
      UID: null
      args:
      - --query.base-path=/jaeger
      enabled: false
      image:
        name: jaegertracing/all-in-one
        pullPolicy: ""
        version: 1.60.0
      nodeSelector:
        kubernetes.io/os: linux
      resources:
        cpu:
          limit: null
          request: null
        ephemeral-storage:
          limit: ""
          request: ""
        memory:
          limit: null
          request: null
      tolerations: null
    linkerdNamespace: linkerd
    linkerdVersion: edge-24.9.1
    namespaceMetadata:
      image:
        name: extension-init
        pullPolicy: ""
        registry: cr.l5d.io/linkerd
        tag: v0.1.1
      nodeSelector:
        kubernetes.io/os: linux
      tolerations: null
    nodeSelector:
      kubernetes.io/os: linux
    podLabels: {}
    revisionHistoryLimit: 10
    tolerations: null
    webhook:
      GID: null
      UID: null
      caBundle: ""
      collectorSvcAccount: collector
      collectorSvcAddr: collector.linkerd-jaeger:55678
      crtPEM: ""
      externalSecret: false
      failurePolicy: Ignore
      image:
        name: cr.l5d.io/linkerd/jaeger-webhook
        pullPolicy: ""
        version: edge-24.9.1
      injectCaFrom: ""
      injectCaFromSecret: ""
      keyPEM: ""
      logLevel: info
      namespaceSelector:
        matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
          - kube-system
      nodeSelector:
        kubernetes.io/os: linux
      objectSelector: null
      replicas: 1
      resources:
        cpu:
          limit: null
          request: null
        memory:
          limit: null
          request: null
      tolerations: null
