apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-smi
  namespace: linkerd-smi
spec:
  interval: 30m
  targetNamespace: linkerd-smi
  dependsOn:
    - name: linkerd
      namespace: linkerd
  releaseName: linkerd-smi
  chart:
    spec:
      chart: linkerd-smi
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
      interval: 12h
