---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: mastodon
  namespace: default
spec:
  interval: 24h
  chart: ./
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: GitRepository
    name: mastodon
