apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mastodon-pvc
  namespace: default
spec:
  resources:
    requests:
      storage: 25Gi
  storageClassName: nfs-client-ssd
  accessModes:
    - ReadWriteMany
