apiVersion: v1
kind: Secret
metadata:
    name: mastodon-secret
    namespace: default
type: Opaque
stringData:
    SECRET_KEY_BASE: ""
    OTP_SECRET: ""
    ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: ""
    ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: ""
    ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: ""
    VAPID_PRIVATE_KEY: ""
    VAPID_PUBLIC_KEY: ""
    postgres-password: ""
    password: ""
    redis-password: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qd2k83kj5ket4qp63rfa456pt5amx5j58sx0dk204crfsmjqvpks4jucs2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxd3dRV3dIU0FkLzVwbGhI
            ckJpdEc1YzF0VlRHSCtET1dJRlAxWWVjTXlJCkpWb1pXWlNZVi9FR1dEN0FBZnk1
            ZDlwV25laWF3Zy9zYXRkaVFxU3MwdnMKLS0tIEJrV3JCa2pyR1dwclJuNEt1WjlN
            bGdDVzRoSlU3WVptN0M3RmdyVFdvL0UKyTD5ECcr9mFsHY7yoakgCC+c8kZ0t+uh
            QvLhi7/s5X7OV23Xb2PiadOZ4Ksn21vL3lz8vfdbyguD8VYtP6Vy6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-21T20:50:22Z"
    mac: ENC[AES256_GCM,data:okkLOJfClg8NgJ0RHVD0nle00BU3gNBNVfpBrKKvp7+RsW8y0VRElcwEqARtcNUmtyaZd2uvWYbhB2SZ1BPyp3Bpgcm7MtKRYD+Iw63tSO8EPLGBXH4JszZPesQPizN4lxKDdVHLbX4hac7p0bNOZ/Or7cHVPQD+udUgVWDrI30=,iv:MPbSoXwPRKYcxRDz2Xjpg07Y7G+WJhT7sb5eFv6B6wA=,tag:niXFCeQq2rjWt34Amh883A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
