apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mastodon-system
  namespace: default
spec:
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client-ssd
  accessModes:
    - ReadWriteMany
