apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: overseerr
  namespace: default
spec:
  chart:
    spec:
      chart: overseerr
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 5.4.2
  interval: 10m0s
  install:
    createNamespace: true
    remediation:
      retries: 50
  upgrade:
    remediation:
      retries: 50
  values:
    global:
      labels:
        app: overseerr
    #podAnnotations:
      #instrumentation.opentelemetry.io/inject-nodejs: "default/nodejs-instrumentation"
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    image:
      repository: sctx/overseerr
      tag: 6d82eee6566492474510480dba7f86f4480d5b88
      pullPolicy: IfNotPresent
    env:
      TZ: America/Chicago
    persistence:
      config:
        enabled: true
        mountPath: /app/config
        storageClass: openebs-hostpath
        size: 10Gi
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/enable: "true"
          hajimari.io/group: Media
          hajimari.io/icon: mdi:movie
#          nginx.ingress.kubernetes.io/service-upstream: "true"
        hosts:
          - host: &host overseerr.internal.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: overseerr-tls
