apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:zACwYlwFttUOWjbT+X/g8OH0cgrKXpyssf6PlewpA7w=,iv:r0W4y1k1BVUL0/3jUWVeziUtlz/R+Z5LRONFfKq9TZU=,tag:StkvwcnqC4Hu+JZE1gU+Ew==,type:str]
