apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:DhMPJdKQzLPeJR34M8O+uIhIUs+kvmVK4sMyBhFDApk=,iv:vU2eYtWf41Pg392f28HP8LoiZEteKaAummLGYslYrIM=,tag:63jfnoviTcuTkkKgNce6PQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qd2k83kj5ket4qp63rfa456pt5amx5j58sx0dk204crfsmjqvpks4jucs2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHOWtVNHJhUHI5WWFBRFdn
            Q1prTnJGZEpFci8rdkxLU1BSaHVQcDhHMDBBCmhSSU9iVEtRODF3Y3VJWk11emky
            NWxQUmdHSXpWQllCYVBSTmJGdXRyWmcKLS0tIEJMT3RnQncra2xrOTRUVlpNTDdx
            RW9JTmVFd3VpT0ozMENEZFJsdHI0MzAKBjob7CenaiGbsYWzuwUr2Kfe+capAMYT
            d+iTXV+hcMZVRhW/bXz/TnAF3NsT3OcJaiXJjbJ99T+snf+8hHkzQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-17T18:34:12Z"
    mac: ENC[AES256_GCM,data:EZ5t24rphchlp1wt4dRRH+vWmJFu/6BjFB+93kAkZUfTHd2OYhortd5k1xuDwfUCvmEjRlBHaxxv2D2SxZZiy5ABU7D6R+BOU4joyyzfxOXBoU/mTV1bd5GSvK7s8OZsqhRl2XlDPzvkrAbHok8vlKIU+9IFVpfzm+63V/V18f4=,iv:KYLOcWJkBVCZj7Yq6kYKA5wg5Q8X+UMaHU0PjsTR5nI=,tag:0cH4HzEFAfb7s0Ut7X6C2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
