apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:NAr6qY4ckMVB5wOhtzVpfszi/4Jeku5A1tNYUN5ZEo4=,iv:i1tckIOuCMD6LnsNjjvpuPip+YvNefKZ/79lwDgJXaE=,tag:ll8hvXgtojDuJH22IoulbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qd2k83kj5ket4qp63rfa456pt5amx5j58sx0dk204crfsmjqvpks4jucs2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3N1M0SWloMmtQNFVGSm41
            MVkvZXVCZ3BRQ2NXeTgveStiZ1YrVHpXalFrCkRMYXIraFZxa3BJVExFa0dKeExI
            Y24xQStVTWRaTVE1eWhjSjc4ak9rYlUKLS0tIGRIVXF0eHROcVB4RE9va0FQNGpo
            Tkp4Y0hQQzdqUTBGSXpxeXlwZTUvdUEK9Owru8KddGd7QPR7WzG4QhrGpS8QU95r
            PGM/Dt7EvfDx1V9HHN1nous2DSnC8S+1kiV/E/R9ruLNksKC2i9vpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-30T17:47:40Z"
    mac: ENC[AES256_GCM,data:Zq8VVkM2By78puOcyQFOY68mU23VkCsiHuFR6hTYeO6FQCDMnChEimUBTc7Qh71QuFUTchHf5wdk/89PfhwJaE9l3ydEFizcPHtBQFatrDvEHE9sLa9/KTPQtblAkTR2Y4FqdcJFim5PSj3t9DWq/Y5E4N0Uq2QN2vtjmA4HznI=,iv:RlT0loF/3eBTvyMqBodveH8x/NBrJqVb1lvRBJGJEMQ=,tag:5MXuKFL0VE2QWGapfQTSeA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
