---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: trust-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 24h0m0s
  releaseName: trust-manager
  targetNamespace: cert-manager
  values:
    secretTargets:
      enabled: true
      authorizedSecretsAll: true
