{
 "title": "Istio Ztunnel Dashboard",
 "description": "Istio Ztunnel Dashboard version 1.23-alpha.c28ee2fb197d92b2cc5aac97761c6394d08719c9",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ztunnel Versions",
   "type": "timeseries",
   "description": "Version number of each running instance",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(istio_build{component=\"ztunnel\"}) by (tag)",
     "legendFormat": "Version ({{tag}})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage of each running instance",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  container_memory_working_set_bytes{container=\"istio-proxy\", pod=~\"ztunnel-.*\"}\n)",
     "legendFormat": "Container ({{pod}})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage of each running instance",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by (pod) (\n  irate(\n    container_cpu_usage_seconds_total{container=\"istio-proxy\", pod=~\"ztunnel-.*\"}\n  [$__rate_interval])\n)",
     "legendFormat": "Container ({{pod}})"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Connections opened and closed per instance",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(\n    istio_tcp_connections_opened_total{pod=~\"ztunnel-.*\"}\n  [$__rate_interval])\n)",
     "legendFormat": "Opened ({{pod}})"
    },
    {
     "expr": "-sum by (pod) (\n  rate(\n    istio_tcp_connections_closed_total{pod=~\"ztunnel-.*\"}\n  [$__rate_interval])\n)",
     "legendFormat": "Closed ({{pod}})"
    }
   ]
  },
  {
   "title": "Bytes Transmitted",
   "type": "timeseries",
   "description": "Bytes sent and recieved per instance",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(\n    istio_tcp_sent_bytes_total{pod=~\"ztunnel-.*\"}\n  [$__rate_interval])\n)",
     "legendFormat": "Sent ({{pod}})"
    },
    {
     "expr": "sum by (pod) (\n  rate(\n    istio_tcp_received_bytes_total{pod=~\"ztunnel-.*\"}\n  [$__rate_interval])\n)",
     "legendFormat": "Received ({{pod}})"
    }
   ]
  },
  {
   "title": "DNS Request",
   "type": "timeseries",
   "description": "DNS queries recieved per instance",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(\n    istio_dns_requests_total{pod=~\"ztunnel-.*\"}\n  [$__rate_interval])\n)",
     "legendFormat": "Request ({{pod}})"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "XDS",
   "type": "timeseries",
   "description": "Count of XDS connection terminations.\nThis will typically spike every 30min for each instance.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(\n    istio_xds_connection_terminations_total{pod=~\"ztunnel-.*\"}\n  [$__rate_interval])\n)",
     "legendFormat": "XDS Connection Terminations ({{pod}})"
    }
   ]
  },
  {
   "title": "Workload Manager",
   "type": "timeseries",
   "description": "Count of active and pending proxies managed by each instance.\nPending is expected to converge to zero.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by (pod) (workload_manager_active_proxy_count{pod=~\"ztunnel-.*\"})",
     "legendFormat": "Active Proxies ({{pod}})"
    },
    {
     "expr": "sum by (pod) (workload_manager_pending_proxy_count{pod=~\"ztunnel-.*\"})",
     "legendFormat": "Pending Proxies ({{pod}})"
    }
   ]
  }
 ]
}