---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 62.7.0
  interval: 1h0m0s
  releaseName: kube-prometheus-stack
  targetNamespace: monitoring
  install:
    crds: Create
  upgrade:
    crds: Create
  driftDetection:
    mode: enabled
    ignore:
      - paths:
          - "/metadata/annotations/prometheus-operator-validated"
        target:
          kind: PrometheusRule
  valuesFrom:
    - kind: ConfigMap
      name: flux-kube-state-metrics-config
      valuesKey: kube-state-metrics-config.yaml
  values:
    namespaceOverride: "monitoring"
    defaultRules:
      rules:
        kubeProxy: false
    alertmanager:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: internal
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - alertmanager.internal.${SECRET_DOMAIN}
        paths:
          - /
        tls:
          - secretName: alertmanager-general-tls
            hosts:
              - alertmanager.internal.${SECRET_DOMAIN}
    grafana:
      image:
        # -- The Docker registry
        registry: docker.io
        # -- Docker image repository
        repository: grafana/grafana
        # Overrides the Grafana image tag whose default is the chart appVersion
        tag: 11.2.0
      sidecar:
        prune: true
        datasources:
          enabled: true
      ingress:
        enabled: true
        ingressClassName: internal
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - grafana.internal.${SECRET_DOMAIN}
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.internal.${SECRET_DOMAIN}
    kubeApiServer:
      enabled: true
      tlsConfig:
        insecureSkipVerify: true
    kubelet:
      enabled: true
    kubeControllerManager:
      enabled: true
      service:
        enabled: true
        port: 10257
        targetPort: 10257
        selector:
          k8s-app: kube-controller-manager
      serviceMonitor:
        insecureSkipVerify: true
    coreDns:
      enabled: true
      service:
        enabled: true
        selector:
          k8s-app: kube-dns
    kubeEtcd:
      enabled: true
      endpoints:
        - 192.168.1.135
      service:
        enabled: true
    kubeScheduler:
      enabled: true
      service:
        enabled: true
        port: 10259
        targetPort: 10259
        selector:
          k8s-app: kube-scheduler
      serviceMonitor:
        insecureSkipVerify: true
    kubeProxy:
      enabled: false
      service:
        enabled: true
        selector:
          k8s-app: kube-proxy
    prometheus:
      prometheusSpec:
        retention: 24h
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        podMonitorNamespaceSelector: { }
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
#        additionalScrapeConfigs:
#          - job_name: 'istiod'
#            kubernetes_sd_configs:
#              - role: endpoints
#                namespaces:
#                  names:
#                    - istio-system
#            relabel_configs:
#              - source_labels: [ __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name ]
#                action: keep
#                regex: istiod;http-monitoring
#          - job_name: 'envoy-stats'
#            metrics_path: /stats/prometheus
#            kubernetes_sd_configs:
#              - role: pod
#            relabel_configs:
#              - source_labels: [ __meta_kubernetes_pod_container_port_name ]
#                action: keep
#                regex: '.*-envoy-prom'
