---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 62.7.0
  interval: 1h0m0s
  releaseName: kube-prometheus-stack
  targetNamespace: monitoring
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      - paths:
          - "/metadata/annotations/prometheus-operator-validated"
        target:
          kind: PrometheusRule
  valuesFrom:
    - kind: ConfigMap
      name: flux-kube-state-metrics-config
      valuesKey: kube-state-metrics-config.yaml
  values:
    namespaceOverride: "monitoring"
    defaultRules:
      rules:
        kubeProxy: false
    alertmanager:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: internal
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - alertmanager.internal.${SECRET_DOMAIN}
        paths:
          - /
        tls:
          - secretName: alertmanager-general-tls
            hosts:
              - alertmanager.internal.${SECRET_DOMAIN}
    grafana:
      image:
        registry: docker.io
        repository: grafana/grafana
        tag: 11.2.1
      plugins:
        - https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip;grafana-lokiexplore-app
      sidecar:
        prune: true
        datasources:
          enabled: true
        dashboards:
          enableNewTablePanelSyntax: true
          resource: both
          folderAnnotation: grafana-dashboard-folder
          provider:
            allowUiUpdates: true
            foldersFromFilesStructure: true
      ingress:
        enabled: true
        ingressClassName: internal
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/service-upstream: "false"
        hosts:
          - grafana.internal.${SECRET_DOMAIN}
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.internal.${SECRET_DOMAIN}
      persistence:
        type: pvc
        enabled: true
        size: 5Gi
        storageClasName: nfs-client-ssd
    kubeApiServer:
      enabled: true
      tlsConfig:
        insecureSkipVerify: true
    kubelet:
      enabled: true
    kubeControllerManager:
      enabled: true
      service:
        enabled: true
        port: 10257
        targetPort: 10257
        selector:
          k8s-app: kube-controller-manager
      serviceMonitor:
        insecureSkipVerify: true
    coreDns:
      enabled: true
      service:
        enabled: true
        selector:
          k8s-app: kube-dns
    kubeEtcd:
      enabled: true
      endpoints:
        - 192.168.1.135
      service:
        enabled: true
    kubeScheduler:
      enabled: true
      service:
        enabled: true
        port: 10259
        targetPort: 10259
        selector:
          k8s-app: kube-scheduler
      serviceMonitor:
        insecureSkipVerify: true
    kubeProxy:
      enabled: false
      service:
        enabled: true
        selector:
          k8s-app: kube-proxy
    prometheus:
      thanosService:
        enabled: true
      thanosServiceMonitor:
        enabled: true

      prometheusSpec:
        enableRemoteWriteReceiver: true
        persistentVolumeClaimRetentionPolicy:
          whenDeleted: Retain
          whenScaled: Retain
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-client-ssd
              accessModes: [ "ReadWriteMany" ]
              resources:
                requests:
                  storage: 50Gi
        retention: 365d
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        additionalScrapeConfigs:
          - job_name: 'adguard'
            static_configs:
              - targets: [ '192.168.1.164:9618/metrics' ]
