---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 62.6.0
  interval: 1h0m0s
  releaseName: kube-prometheus-stack
  targetNamespace: monitoring
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      - paths:
          - "/metadata/annotations/prometheus-operator-validated"
        target:
          kind: PrometheusRule
  valuesFrom:
    - kind: ConfigMap
      name: flux-kube-state-metrics-config
      valuesKey: kube-state-metrics-config.yaml
  values:
    alertmanager:
      enabled: false
    grafana:
      ingress:
        enabled: true
        ingressClassName: internal
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - grafana.internal.${SECRET_DOMAIN}
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.internal.${SECRET_DOMAIN}
    prometheus:
      prometheusSpec:
        retention: 24h
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        podMonitorNamespaceSelector: { }
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        additionalScrapeConfigs:
          - job_name: 'istio-mesh'
            scrape_interval: 5s
            kubernetes_sd_configs:
              - role: endpoints
                namespaces:
                  names:
                    - istio-system
            relabel_configs:
              - source_labels: [ __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name ]
                action: keep
                regex: istio-telemetry;prometheus
          - job_name: 'envy'
            scrape_interval: 5s
            kubernetes_sd_configs:
              - role: endpoints
                namespaces:
                  names:
                    - istio-system
            relabel_configs:
              - source_labels: [ __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name ]
                action: keep
                regex: istio-statsd-prom-bridge;statsd-prom
          - job_name: 'istio-policy'
            scrape_interval: 5s
            kubernetes_sd_configs:
              - role: endpoints
                namespaces:
                  names:
                    - istio-system
            relabel_configs:
              - source_labels: [ __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name ]
                action: keep
                regex: istio-policy;http-monitoring
          - job_name: 'istio-telemetry'
            scrape_interval: 5s
            kubernetes_sd_configs:
              - role: endpoints
                namespaces:
                  names:
                    - istio-system
            relabel_configs:
              - source_labels: [ __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name ]
                action: keep
                regex: istio-telemetry;http-monitoring
          - job_name: 'pilot'
            scrape_interval: 5s
            kubernetes_sd_configs:
              - role: endpoints
                namespaces:
                  names:
                    - istio-system
            relabel_configs:
              - source_labels: [ __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name ]
                action: keep
                regex: istio-pilot;http-monitoring
          - job_name: 'galley'
            scrape_interval: 5s
            kubernetes_sd_configs:
              - role: endpoints
                namespaces:
                  names:
                    - istio-system
            relabel_configs:
              - source_labels: [ __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name ]
                action: keep
                regex: istio-galley;http-monitoring
