apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: v1
    datasources:
      - name: InfluxDB
        type: influxdb
        typeName: InfluxDB
        typeLogoUrl: public/app/plugins/datasource/influxdb/img/influxdb_logo.svg
        uid: influxdb
        url: http://192.168.1.166:8086
        basicAuth: false
        isDefault: false
        jsonData:
          httpMode: POST
          organization: proxmox
          tlsSkipVerify: true
          version: Flux
        secureJsonData:
          token: ${INFLUXDB_API_TOKEN}
