apiVersion: v1
kind: Secret
metadata:
    labels:
        grafana_datasource: "1"
    name: influx-datasource
    namespace: monitoring
type: Opaque
data:
    datasource.yaml: ENC[AES256_GCM,data:sAVpPId/7mg48E1xhjUZ3SsW3R+0RPCslgwHYbvwD0aK8ye1gQJRoYzOHpy/kj6LEP+GW+TvI9WzCE6lMCoHiWF+GuoNTyUtY056YpmUz6Yvd11KN1c3YL+zZxZeNy9qgbsv06MUYvnD1yCRP1wsLUsO1rFtNs8xzaXcbn9NE+gxNTSoApfep13cJ23SU01vBbmwqnEFISTIAlQxJSClGnaOrJlmXAmFRxHsn+7P5RgqTCtKBIqPwmRq5S3KJiyeCZdkXz8hLtjT6LI/tFpGKdW9ATOfTN5tFFLl+bjx2Mqq5D3qke49OEP9ZpwIEdbIcoVuWmr0ouWndCQUWjLVSs9Wu7zi/8t0NTOLdY37EoN5Bg8t5MupWoRLcupLXGCL0edVUlu+UDmHJ5ZCIaDOSZFQyb+vGRUAbJjNbXWfU4JDP+XQ4xEWh/0ZmKDndZBZXtQphvdBBhHyzQ7Zse9hK16qNzgUqFA4+cMJMBut03dwDL7ZHoW4e6xj62NcXM5cTh4lnxRAFxtS9auv6raS9qN3rcu7ApiYou7YuJ0exH2+MhXNgF2OJm+JwxbiTeSLOJbp0zkLhaMicZEX+pc5N6XJ+WFUaeVPxoyB5XY3LjSLr5Ku4UP3vi3XJH+4w1E8LNjqXUWLvgPPB6A=,iv:EI6FMQlJkQHwzRVLRoaGnTy9Z7f8HvzvZxo2L9D2kQs=,tag:qr4dusogt5e3R4lPzK30DQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19jc9zp5pc7me0wkx28kc2ypr9qh6t9zphn3fdk63ae9dz9a2h5gsh4w866
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TzRRWUVneGtmR2hDNGls
            Q2hJWk9zWVByZ0xrMXI3aDZ3OS9lb3p6V0Q0CnJ1VDJuUTFPSmJUYmVlejk5bm9j
            UUM4YXJPSy94czQ4OXBnSFc0V1BRSHcKLS0tIG9rTTZsbk9mQ29vRXhuNlNkNldD
            c2hQc1AvV1ZiZHVmQ1huby8wN2dQdk0KCM65i3gJ689sX72sgEPS9bzt63Mt4Nlx
            DcbQiWgEZhq2peTfEApdiwx3YQ5YfuJqhSqS1MN2axzUCsC7c0WguQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-03T17:30:19Z"
    mac: ENC[AES256_GCM,data:6sC2IoaGpAKjMrHnAAvNddxyCTHp7qjv8C/T160h7f39iQtj1MwcYPwe2eYAiQFgL8uhxtwfGAOuGtK4LJpSWqXSP/HPJHQ8wwK2NVoWO9zLE9/4f1yFRXRXRQPg/d2kRf/tdUy//4cB8F2J4EY1YIohMQ3Emdk+sHfLaYzWf+o=,iv:BlGOdG++jKpmmV2gmWvxdSQiFX8lwIKm4TVL+NaiwCw=,tag:saSRYzC6DP8BLLLUkJ7WeA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
