apiVersion: v1
kind: Secret
metadata:
    labels:
        grafana_datasource: "1"
    name: influx-datasource
    namespace: monitoring
type: Opaque
stringData:
    datasource.yaml: ENC[AES256_GCM,data:BT7FaS+AF6e/JJsQRqDO+W3n0+4LrlqZnzxNebzgvbq7TpPfKFY3NWqvvBd4/2APTziDMkF17ljD22AfAHe80s+QLxl/3lwaOfDJElsk0O9/WvIu3/os6lw1IElHFIRp54Qb/JUljxIhXcf1nx+MI1xCZh48mcWPrR4ULJqWZbAQefMTUa9alQ4zNfZL2B+86Y4AIlHVgq8jawte94tU3gVMIMBrOfhyx0aUg/qbgU0yC8eX64C1v6KxmRFcd3inKf5/S2YZ+bOq/2K9fNfG7ZhfNDevSMMO4Hi37W4ThjimLUZIw69f7tDHd4aW3vUqbeTsuxtFrAhE58S3fZD1VZ5kIxFsY34Lu933j/GtN+Wu3vJIYdENO9jctTQVm7POeXG2RN1IUMU9z92bXsTlGf0oLw9CPt7JomQQ5KvWi1NkPdxEkmH2hK+C37MY6QsI7lq910ogAiuF2ZhmPm9HEQyxZRN7MDkfW1d21kjVozmOeeDjIw9ysN28A4mHmLFCYBVGxd8Wtnf1ZwRDbYOhsfoUpM1APMN87n/462JOcVf8aNL80fehn6UhuJF9QsRF1BVzHUckiegGh9IcQHbwcN7AygZCdwS8edtiY3HqsQCVbShBnzpvToQDWlKnIR5Q2yFm+EixrhUBPVthYg==,iv:lTM9txwW7DxDphtITxtYY99yOWOj1Enta1na8SllYrc=,tag:zYspLx9oGQFOPu4qOFP2Mg==,type:str]
