apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: default
spec:
  ports:
    - port: 8086
      name: http
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: influxdb
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.1.166
    ports:
      - port: 8086
