---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    provider: webhook
    sidecars:
      - name: adguard-webhook
        image: ghcr.io/muhlba91/external-dns-provider-adguard:v8.0.0
        ports:
          - containerPort: 8888
            name: http
          - containerPort: 8080
            name: healthz
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          timeoutSeconds: 5
        env:
          - name: LOG_LEVEL
            value: debug
          - name: ADGUARD_URL
            valueFrom:
              secretKeyRef:
                name: adguard-configuration
                key: url
          - name: ADGUARD_USER
            valueFrom:
              secretKeyRef:
                name: adguard-configuration
                key: user
          - name: ADGUARD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: adguard-configuration
                key: password
          - name: DRY_RUN
            value: "false"
    #    env:
    #      - name: CF_API_TOKEN
    #        valueFrom:
    #          secretKeyRef:
    #            name: external-dns-secret
    #            key: api-token
    extraArgs:
      - webhook-provider-url: http://localhost:8888
    #      - --ingress-class=external
    #      - --cloudflare-proxied
    #      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
    #      - --crd-source-kind=DNSEndpoint
    policy: sync
    sources: [ "crd", "ingress" ]
    txtPrefix: k8s.
    txtOwnerId: default
    domainFilters: [ "${SECRET_DOMAIN}" ]
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: adguard-configuration
