apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:2rLv8B7SgFfW4anu++UH/PCQ8BIG069MldeA38SoYiHoUI9qd1ZYbw==,iv:aBVu8jsaMAwi1dKk5SnwSvwFAaB1pOhFWn+wq8ZSW5I=,tag:8/jlH5U//bkFDqXRelkD/g==,type:str]
