apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:+iHdWv9m8rbuRiUkQO+avLIvZOnjePP0IMgjGwRfJHWv9BSg0uy1fw==,iv:BE6RF7a8c3vSfNLn6mZ7UlqyFGTcwSIty8+aCv1KSXI=,tag:dqbm+F4XN70fqGEbUDqIUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qd2k83kj5ket4qp63rfa456pt5amx5j58sx0dk204crfsmjqvpks4jucs2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiS2NuU0dnZ0tDQmZvTzZp
            dWRFOTUzaG01SkRDTjNHYnNiNjBBRVg2ZGlVCjZRelJPd21OTzdManBMeUJ0MGJj
            UXJWMWwrM2J1eFEybkRLaEJUaE1VclkKLS0tIGNJNGM5b25uaktGM2JGdjdlZTdx
            WkE5MkxJWU9rQXlXR0ErUkZNSW9KaDQK4369dWRWyoasHCNaJPhKyQ6OB7HY1W0L
            UOFWpYvtdjWTMtchcDhK32HsdTY0ZvRCC9BRJ4ULvt2R6UzSJyArGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-17T18:34:12Z"
    mac: ENC[AES256_GCM,data:YEJ3Yvz9QsoQOEzR8YT5EYr3RaEN5eDPMkV7q076t4ri30yBjy7CA+kOyuZg+fruTWRG1za8maV7PTA/H4VPakXgQV01wnPC5nsWq0Ur2NR/6N7IJI99mRitPcVB/NSqo84Gxd+c289aOttSUFGQwDxy0Y6SaRS8+njP3YzTf64=,iv:z0BMunQNfQv4c2nOhWnjftIMHGBDxSBdgwIpvPSLXKE=,tag:4lCf0sWwpyjckJm10ows5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
