apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:LlqEK/l7/hvTqQptlj7eiisNOT62C8OWdGX3PjVAtDqD3DP8YeDVuQ==,iv:mMBX43TS8nc8HRllRf02F6bWvZMQOAtPpG5wA70uzG0=,tag:EWYILpn/OPu/h+oNkZt4gA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19jc9zp5pc7me0wkx28kc2ypr9qh6t9zphn3fdk63ae9dz9a2h5gsh4w866
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2amQvZTQ3TlVadW1Cbm1L
            dG1aK2t4WnhLaTkxY2p1ZkpuNDFjOGpZQ2hnCk9EYUFpWkFkeFRFOGtXWHRnRUpl
            VEVTQ2NXNzZuR2ttUHhjNmdOcEU5MUEKLS0tIEdoY3JMNUJmRnFzcC84a3Y0cVpt
            a1R6R2MybDVZVVRPZHlIelJXRk5lUVUKudjesBVc0e2NkBlFbi9vTEA6jiXs8Qya
            wWowwi98jUxTJu2uNw0Cuioe2DUfJT5Vj1p85yBjVjHmx//HgAGitQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-02T16:48:19Z"
    mac: ENC[AES256_GCM,data:VyZI6hio6gS9BugkdGkqSzYHlfvg6Gi46fvK6RUrauk01hMD7Dkn/QB/0nnaK5UGLomcpYZiF4VRmA7Hc/C4fLXxDXXqUnDtDLqfvCIuf4ysCbZEF1YR8uK7jC4MwvdVcwpjxAO/18OyOUCoKVajM1xtKf3HodYAgngR0wkz/04=,iv:4FWB9UQ4E86RsidBnQrlaW/hOmX8O9e/VwZeCbdAMk4=,tag:vsSIC0C8nZw3KOJkw6C1Ag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
