apiVersion: v1
kind: Namespace
metadata:
  name: portainer
  labels:
    istio-injection: disabled
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
