---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  chart:
    spec:
      chart: portainer
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: portainer
        namespace: flux-system
  interval: 1h0m0s
  releaseName: portainer
  targetNamespace: portainer
  values:
    enterpriseEdition:
      enable: true
      image:
        repository: portainer/portainer-ee
        tag: 2.21.1
        pullPolicy: Always
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: cilium
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        nginx.ingress.kubernetes.io/service-upstream: "false"
      hosts:
        - host: portainer.internal.${SECRET_DOMAIN}
          paths:
            - path: "/"
      tls:
        - hosts:
            - portainer.internal.${SECRET_DOMAIN}
          secretName: portainer-tls
    persistence:
      storageClass: openebs-hostpath
