---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: robusta
  namespace: monitoring
spec:
  chart:
    spec:
      chart: robusta
      interval: 24h0m0s
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: robusta
        namespace: flux-system
      version: 0.18.0
  interval: 24h0m0s
  releaseName: robusta
  targetNamespace: monitoring
  install:
    remediation:
      retries: 5
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
  values:
    clusterName: home-kubernetes
    enableHolmesGPT: false
    enablePlatformPlaybooks: true
    enablePrometheusStack: false
    enabledManagedConfiguration: true
    globalConfig:
      account_id: '{{ env.ACCOUNT_ID }}'
      grafana_api_key: '{{ env.GRAFANA_KEY }}'
      grafana_url: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:3000
      prometheus_url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
      signing_key: '{{ env.SIGNING_KEY }}'
    isSmallCluster: true
    runner:
      additional_env_vars:
      - name: GRAFANA_KEY
        valueFrom:
          secretKeyRef:
            key: GRAFANA_TOKEN
            name: robusta-secrets
      - name: SIGNING_KEY
        valueFrom:
          secretKeyRef:
            key: SIGNING_KEY
            name: robusta-secrets
      - name: ACCOUNT_ID
        valueFrom:
          secretKeyRef:
            key: ACCOUNT_ID
            name: robusta-secrets
      - name: SINK_TOKEN
        valueFrom:
          secretKeyRef:
            key: SINK_TOKEN
            name: robusta-secrets
      - name: ROCKETCHAT_USER_ID
        valueFrom:
          secretKeyRef:
            key: ROCKETCHAT_USER_ID
            name: robusta-secrets
      - name: ROCKETCHAT_TOKEN
        valueFrom:
          secretKeyRef:
            key: ROCKETCHAT_TOKEN
            name: robusta-secrets
      sendAdditionalTelemetry: false
    sinksConfig:
    - robusta_sink:
        name: robusta_ui_sink
        token: '{{ env.SINK_TOKEN }}'
    - rocketchat_sink:
        name: main_rocketchat_sink
        user_id: '{{ env.ROCKETCHAT_USER_ID }}'
        channel: notifs
        token: '{{ env.ROCKETCHAT_TOKEN }}'
        server_url: http://rocket-chat-rocketchat.default.svc.cluster.local
