apiVersion: v1
kind: Secret
metadata:
    name: robusta-secrets
    namespace: monitoring
type: Opaque
stringData:
    GRAFANA_TOKEN: ENC[AES256_GCM,data:/PMNjeo+4bHq6figvWvs8Ou/C38Gl3V8E69PpyVVCRZIZVu7TLxKxGjJZnXNig==,iv:HKAQPtStY6U5jq6EvLrCvR9UTjOaTg7Xl81yTq+Yhy4=,tag:ncA5ZV+YwzhbZEXcisfYYg==,type:str]
    SIGNING_KEY: ENC[AES256_GCM,data:F/47CCg64No1jA6KPFAXlPVbEt1vcsMjiTfnVZpF7vi0oYM3,iv:dbidmJ13oajZjstJ4f+5+lffRIjm87ocuiGIiAzBFt4=,tag:z4h+h9aJ5a5JrGRe7QuuFg==,type:str]
    ACCOUNT_ID: ENC[AES256_GCM,data:wgDAB5Uz0si85juaNzoBpKTNd3v0e69rJvKpJV9FmpmkmU/m,iv:mgrQGtPi+WckJ4Fh7P3YnJwVO4gdHI+40jH6cSVAKSo=,tag:VbpAnc6vNCMaYlw3Oi8qvA==,type:str]
    SINK_TOKEN: ENC[AES256_GCM,data:Aq1N8VvwgRQfVYGN84FEkWU55fYMhynJK781j5ZNTyhRVklQwQf7aLfFzl+Xkn6e4aaFklsl9KgCSI9XfnhXB3EcldZHO8V/hIyg/muQdUGbgK2sFXrg4CSto9Q5FvATpuA+shlE+FGaIOUr0qKSAvneLxrRvxUXmodYsuj9gsWJidKX/gGAPDYqcSUpr7Or+WX6naohfD5dFMNUk1rbkRHlyWif/FhY8Wyf4i2uycy7haZoQFr+xHDyyDP+hv2A6V2uXaltl5tPNltEb8PupZEoTj6+RfcF/qusGel6/MjDkMMNEpMFJOIltqX5u8V9KOkhzC+su1exZFg5IXh4xPHvFMNmTy0Zq9E7s1kbJyi8GETDJJHIEwZIAPcLYa660YqK7GnGuG1Cb424zMeGiw85hWl1A7OOJ1eKHPpKOwd4GLb454LJ87E1qYOx1siekrSRJzYy3rit8ZgbLRxCjqAm8INGMcl4M5ExApfdZ8JXLewAQeQTTkliris2skA35nN+Aqch6ByGqwmNgaYWFmSz9MoZL8SYJMx+Q1b+zdfzRnh9ot/g9yzyrzunCvDoqTwoF9cGZDdSruHjZ0/DmVV2Q8rcmV6JzzIUfFtTDHFymktEAkT2fkhAhf1q5esow/cbiVQxQA3Li1+aiWBxQQ==,iv:Bf8+GcZOxc3++R/61OPbIwaaKxosGRAO1RcYFvLbfLY=,tag:XU9hB4yK712Ylnv5G1OYCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qd2k83kj5ket4qp63rfa456pt5amx5j58sx0dk204crfsmjqvpks4jucs2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMnQzNkZvK1NOanNUZlFV
            ZmN1ZGpIODRmMmh0NmNBdTZGbThhRjJ0S0dRClY1WDFaa2hORUZ2ZlJSbnNPVjdL
            SUdpZFZBNVA2V2dMZHVhNjdaNHFTWW8KLS0tIEpSTWI4bXI2dHpJamh2Mm9oT1dk
            UmcvV1RHRTlsdzQ1Uk53Wk9FTHJjQW8KGFyygKY9CCJveJx5Sh456L5eFSy1JfIn
            e5nmdNy1DwjPZvAeYX5VNKaLnvxrG8QQYYt3T6CswdK8wMGxdmETzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T16:48:06Z"
    mac: ENC[AES256_GCM,data:45r0lK13m0aO50uEkUhIC58dPEZ0Ng2eyHd0wf6yIg8Y5aPfNAo2IiVvG7VF1K2uleeOJFi28fnjiyvmte2rxnZ5ZvQGhcfQLw+m5Iys45Lvg/r9UEsXducYAGU0jx50ypfxYPm8+q2ktIJ5sYSu/YrPlT1+4biTFr61Bc98Zvg=,iv:XNlhh8JxTOWqU/a53FlCsZ26fk69vLp5vZJXEFUz6YY=,tag:rlzhPI82g5b1liWO3p3skg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
