---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: default
spec:
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.5.1
  interval: 12h0m0s
  releaseName: homepage
  targetNamespace: default
  values:
    controllers:
      main:
        containers:
          homepage:
            env:
              - name: TZ
                value: America/Chicago
              - name: PUID
                value: 1000
              - name: PGID
                value: 1000
              - name: HOMEPAGE_VAR_RADARR_APIKEY
                valueFrom:
                  secretKeyRef:
                    name: radarr-apikey
                    key: APIKEY
              - name: HOMEPAGE_VAR_SONARR_APIKEY
                valueFrom:
                  secretKeyRef:
                    name: sonarr-apikey
                    key: API_KEY
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v0.9.12
        enabled: true
        type: deployment
    global:
      fullnameOverride: homepage
      labels:
        app: homepage
    ingress:
      homepage:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        className: internal
        enabled: true
        hosts:
          - host: homepage.internal.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: homepage
        tls:
          - hosts:
              - homepage.internal.${SECRET_DOMAIN}
            secretName: homepage-tls
    persistence:
      config:
        type: configMap
        name: home-settings
        globalMounts:
          - subPath: bookmarks.yaml
            path: /app/config/bookmarks.yaml
          - subPath: docker.yaml
            path: /app/config/docker.yaml
          - subPath: kubernetes.yaml
            path: /app/config/kubernetes.yaml
          - subPath: services.yaml
            path: /app/config/services.yaml
          - subPath: settings.yaml
            path: /app/config/settings.yaml
          - subPath: widgets.yaml
            path: /app/config/widgets.yaml
    service:
      homepage:
        controller: main
        enabled: true
        ports:
          http:
            appProtocol: http
            enabled: true
            port: 3000
            protocol: HTTP
    serviceAccount:
      create: true
    rbac:
      roles:
        homepage:
          enabled: true
          type: ClusterRole
          rules:
            - apiGroups:
                - ""
              resources:
                - namespaces
                - pods
                - nodes
              verbs:
                - get
                - list
            - apiGroups:
                - extensions
                - networking.k8s.io
              resources:
                - ingresses
              verbs:
                - get
                - list
            - apiGroups:
                - traefik.containo.us
              resources:
                - ingressroutes
              verbs:
                - get
                - list
            - apiGroups:
                - metrics.k8s.io
              resources:
                - nodes
                - pods
              verbs:
                - get
                - list
      bindings:
        homepage:
          enabled: true
          type: ClusterRoleBinding
          roleRef:
            identifier: homepage
          subjects:
            - identifier: default
