---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cloudflared/ks.yaml
  - ./echo-server/ks.yaml
  - ./external-dns/ks.yaml
  - ./ingress-nginx/ks.yaml
  - ./k8s-gateway/ks.yaml
#  - ./peer-auth-policy.yaml
configMapGenerator:
  - name: network-dashboards
    namespace: network
    options:
      labels:
        grafana_dashboard: "1"
    files:
      - ./dashboards/nginx-ingress.json
