apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network-namespace-policy
  namespace: network
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 443
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 4317
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 7844
