apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: network-policy
  namespace: network
spec:
  endpointSelector: { }
  ingress:
    - fromEntities:
        - world
    - toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
            - port: "4245"
              protocol: TCP
          rules:
            http: [ { } ]
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toEntities:
        - all
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: ingress-nginx-internal
      toPorts:
        - ports:
            - port: "4317"
              protocol: TCP
          rules:
            http: [{}]
      toEntities:
        - world
