apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: network-policy
  namespace: network
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - {}
    - fromEntities:
        - all
    - toPorts:
        - ports:
            - port: "80"
              protocol: ANY
            - port: "443"
              protocol: ANY
          rules:
            http: [{}]
  egress:
    - toEndpoints:
        - {}
    - toEntities:
        - world
    - toEntities:
        - cluster
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
